"use client";

import {useCallback,useEffect,useState} from "react";
import {requestJson} from "../../client-request";

type Summary={orderCount:number;revenue:number;productRevenue:number;shippingRevenue:number;cogs:number|null;grossProfit:number|null;marginRate:number|null;cogsAvailable:boolean};
type FinanceData={generatedAt:string;pipeline:{TR:Summary;GLOBAL:Summary};realized:{TR:Summary;GLOBAL:Summary};counts:{pendingPayment:number;refunded:number;paid:number};marginAlerts:Array<{id:number;name:string;price:number;cost:number}>;missingCosts:Array<{id:number;name:string}>;recent:Array<{id:number;orderNumber:string;market:"TR"|"GLOBAL";status:string;paymentStatus:string;total:number;productRevenue:number;cogs:number|null;grossProfit:number|null;createdAt:string}>;error?:string};
const statusLabels:Record<string,string>={new:"Yeni",confirmed:"Onaylandı",preparing:"Hazırlanıyor",shipped:"Kargoda",completed:"Tamamlandı"};

export default function FinanceCenter(){
  const[data,setData]=useState<FinanceData|null>(null);const[message,setMessage]=useState("Finans özeti hazırlanıyor…");const[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{setRefreshing(true);try{const{response,data:body,error}=await requestJson<FinanceData>("/api/finance-summary");if(response?.ok&&body){setData(body);setMessage("")}else setMessage(body?.error??error??"Finans özeti alınamadı. Lütfen tekrar deneyin.")}finally{setRefreshing(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const money=(value:number,market:"TR"|"GLOBAL")=>market==="TR"?`${value.toLocaleString("tr-TR",{maximumFractionDigits:2})} TL`:`€${value.toLocaleString("en-US",{maximumFractionDigits:2})}`;
  if(!data)return <main className="admin-shell finance-shell"><a href="/admin">← Yönetim paneli</a><p>{message}</p><button onClick={load} disabled={refreshing}>{refreshing?"Yenileniyor…":"Tekrar dene"}</button></main>;
  const card=(title:string,market:"TR"|"GLOBAL",summary:Summary)=><article className="admin-card finance-card"><p className="section-kicker">{market==="TR"?"TÜRKİYE":"GLOBAL"}</p><h2>{title}</h2><strong>{money(summary.revenue,market)}</strong><span>{summary.orderCount} sipariş · ürün {money(summary.productRevenue,market)} · kargo {money(summary.shippingRevenue,market)}</span><dl><div><dt>Ürün maliyeti</dt><dd>{summary.cogs===null?"Hesaplanamıyor":money(summary.cogs,market)}</dd></div><div><dt>Brüt ürün marjı</dt><dd>{summary.grossProfit===null?"Hesaplanamıyor":money(summary.grossProfit,market)}</dd></div><div><dt>Marj oranı</dt><dd>{summary.marginRate===null?"—":`%${summary.marginRate.toLocaleString("tr-TR",{maximumFractionDigits:1})}`}</dd></div></dl>{!summary.cogsAvailable&&<small>{market==="GLOBAL"?"Global ürün maliyetleri avro bazında tanımlanmadığı için marj gösterilmez.":"Eski siparişlerde veya ürünlerde maliyet kaydı eksik."}</small>}</article>;
  return <main className="admin-shell finance-shell"><header className="admin-header"><div><p>FİNANS VE KÂRLILIK</p><h1>Mali kontrol merkezi</h1></div><div><a href="/admin/stok">Maliyetleri düzenle ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="finance-notice"><b>Operasyonel tahmin</b><p>Bu rapor muhasebe kaydı, gelir tablosu veya vergi beyanı değildir. Vergiler, ödeme sağlayıcısı komisyonları, kargo maliyetleri, iadeler ve genel giderler düşülmemiştir.</p></section><section className="finance-counts"><article><b>{data.counts.paid}</b><span>Ödemesi kayıtlı</span></article><article><b>{data.counts.pendingPayment}</b><span>Ödeme bekliyor</span></article><article><b>{data.counts.refunded}</b><span>İade kaydı</span></article><article className={data.marginAlerts.length||data.missingCosts.length?"warning":""}><b>{data.marginAlerts.length+data.missingCosts.length}</b><span>Maliyet uyarısı</span></article></section><div className="finance-section-title"><p className="section-kicker">TALEP VE SİPARİŞ HAVUZU</p><h2>Potansiyel değer</h2></div><section className="finance-grid">{card("Açık sipariş değeri","TR",data.pipeline.TR)}{card("Open order value","GLOBAL",data.pipeline.GLOBAL)}</section><div className="finance-section-title"><p className="section-kicker">ÖDEMESİ KAYITLI</p><h2>Gerçekleşen operasyonel değer</h2></div><section className="finance-grid">{card("Ödemesi alınan","TR",data.realized.TR)}{card("Paid orders","GLOBAL",data.realized.GLOBAL)}</section>{(data.marginAlerts.length>0||data.missingCosts.length>0)&&<section className="admin-card margin-alerts"><div className="list-title"><div><p className="section-kicker">FİYAT KORUMASI</p><h2>Maliyet kontrolü gereken ürünler</h2></div><span>{data.marginAlerts.length+data.missingCosts.length} uyarı</span></div>{data.missingCosts.map(item=><a href={`/admin/stok`} key={`missing-${item.id}`}><span><b>{item.name}</b><small>Birim maliyet girilmemiş</small></span><i>Eksik →</i></a>)}{data.marginAlerts.map(item=><a href={`/admin/urun/${item.id}`} key={`margin-${item.id}`}><span><b>{item.name}</b><small>Fiyat {money(item.price,"TR")} · maliyet {money(item.cost,"TR")}</small></span><i>Zarar riski →</i></a>)}</section>}<section className="admin-card finance-orders"><div className="list-title"><div><p className="section-kicker">SİPARİŞ BAZINDA</p><h2>Son mali görünüm</h2></div><span>{new Date(data.generatedAt).toLocaleString("tr-TR")}</span></div>{data.recent.map(order=><a href={`/admin/siparis/${order.id}`} key={order.id}><span><b>{order.orderNumber}</b><small>{statusLabels[order.status]??order.status} · {order.paymentStatus} · {new Date(order.createdAt).toLocaleDateString("tr-TR")}</small></span><span><b>{money(order.total,order.market)}</b><small>{order.grossProfit===null?"Maliyet eksik":`Brüt ürün marjı ${money(order.grossProfit,order.market)}`}</small></span></a>)}</section></main>;
}
