"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {requestJson} from "../../client-request";

type Customer={email:string;name:string;maskedPhone:string;city:string;country:string;orderCount:number;activeOrderCount:number;cancelledOrderCount:number;paidOrderCount:number;unverifiedActiveCount:number;totalTr:number;totalGlobal:number;firstOrderAt:string;lastOrderAt:string;lastOrderId:number;lastOrderNumber:string;lastOrderStatus:string};
type CustomerData={generatedAt:string;summary:{customerCount:number;repeatCustomerCount:number;verifiedCustomerCount:number;attentionCount:number};customers:Customer[];error?:string};
type Filter="all"|"repeat"|"attention"|"paid";
const statusLabels:Record<string,string>={new:"Yeni",confirmed:"Onaylandı",preparing:"Hazırlanıyor",shipped:"Kargoda",completed:"Tamamlandı",cancelled:"İptal"};

export default function CustomerCenter(){
  const[data,setData]=useState<CustomerData|null>(null);const[message,setMessage]=useState("Müşteri özeti hazırlanıyor…");const[query,setQuery]=useState("");const[filter,setFilter]=useState<Filter>("all");const[refreshing,setRefreshing]=useState(false);
  const load=useCallback(async()=>{setRefreshing(true);try{const{response,data:body,error}=await requestJson<CustomerData>("/api/customers");if(response?.ok&&body){setData(body);setMessage("")}else setMessage(body?.error??error??"Müşteri özeti alınamadı. Lütfen tekrar deneyin.")}finally{setRefreshing(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const visible=useMemo(()=>{if(!data)return[];const needle=query.trim().toLocaleLowerCase("tr-TR");return data.customers.filter(customer=>{const matchesFilter=filter==="all"||(filter==="repeat"&&customer.orderCount>1)||(filter==="attention"&&customer.unverifiedActiveCount>0)||(filter==="paid"&&customer.paidOrderCount>0);const matchesQuery=!needle||[customer.name,customer.email,customer.city,customer.country,customer.lastOrderNumber].some(value=>value.toLocaleLowerCase("tr-TR").includes(needle));return matchesFilter&&matchesQuery;})},[data,filter,query]);
  const money=(value:number,market:"TR"|"GLOBAL")=>market==="TR"?`${value.toLocaleString("tr-TR",{maximumFractionDigits:2})} TL`:`€${value.toLocaleString("en-US",{maximumFractionDigits:2})}`;
  if(!data)return <main className="admin-shell customer-shell"><a href="/admin">← Yönetim paneli</a><p>{message}</p><button onClick={load} disabled={refreshing}>{refreshing?"Yenileniyor…":"Tekrar dene"}</button></main>;
  return <main className="admin-shell customer-shell"><header className="admin-header"><div><p>MÜŞTERİ OPERASYONLARI</p><h1>Müşteri merkezi</h1></div><div><a href="/admin/operasyon">Operasyonları gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="customer-privacy"><b>Sipariş ilişkisi görünümü</b><p>Bu ekran bir pazarlama listesi değildir. İletişim bilgileri yalnızca sipariş, teslimat ve destek işlemleri için kullanılmalıdır; ayrıca pazarlama izni alınmış kabul edilmez.</p></section><section className="customer-stats"><article><b>{data.summary.customerCount}</b><span>Tekil müşteri</span></article><article><b>{data.summary.repeatCustomerCount}</b><span>Tekrar sipariş</span></article><article><b>{data.summary.verifiedCustomerCount}</b><span>Doğrulama sorunu yok</span></article><article className={data.summary.attentionCount?"warning":""}><b>{data.summary.attentionCount}</b><span>Doğrulama bekliyor</span></article></section><section className="admin-card customer-controls"><label>Müşteri veya sipariş ara<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ad, e-posta, şehir veya sipariş no"/></label><div role="group" aria-label="Müşteri filtreleri">{([['all','Tümü'],['repeat','Tekrar gelen'],['attention','Doğrulama bekleyen'],['paid','Ödemesi kayıtlı']] as Array<[Filter,string]>).map(([key,label])=><button className={filter===key?"active":""} onClick={()=>setFilter(key)} key={key}>{label}</button>)}</div></section><div className="customer-list-title"><div><p className="section-kicker">MÜŞTERİLER</p><h2>Operasyon özeti</h2></div><span>{visible.length} kayıt · {new Date(data.generatedAt).toLocaleString("tr-TR")}</span></div><section className="customer-list">{visible.map(customer=><article className="admin-card" key={customer.email}><div className="customer-identity"><span>{customer.orderCount>1?"TEKRAR GELEN":"İLK SİPARİŞ"}</span><h3>{customer.name}</h3><p>{customer.email}</p><small>{customer.maskedPhone} · {customer.city}, {customer.country}</small></div><dl><div><dt>Sipariş</dt><dd>{customer.orderCount} toplam · {customer.activeOrderCount} aktif</dd></div><div><dt>Ödeme kaydı</dt><dd>{customer.paidOrderCount} sipariş</dd></div><div><dt>Aktif Türkiye talebi</dt><dd>{money(customer.totalTr,"TR")}</dd></div><div><dt>Aktif global talep</dt><dd>{money(customer.totalGlobal,"GLOBAL")}</dd></div></dl><div className="customer-last-order"><span>SON SİPARİŞ</span><b>{customer.lastOrderNumber}</b><small>{statusLabels[customer.lastOrderStatus]??customer.lastOrderStatus} · {new Date(customer.lastOrderAt).toLocaleDateString("tr-TR")}</small>{customer.unverifiedActiveCount>0&&<em>{customer.unverifiedActiveCount} doğrulama bekliyor</em>}<a href={`/admin/siparis/${customer.lastOrderId}`}>Siparişi aç →</a></div></article>)}{visible.length===0&&<p className="admin-card customer-empty">Bu filtreye uygun müşteri kaydı bulunamadı.</p>}</section></main>;
}
