"use client";

import {FormEvent,useEffect,useState} from "react";

type Values={brandName:string;brandSuffix:string;brandLogoUrl:string;faviconUrl:string};
const defaults:Values={brandName:"MYSA",brandSuffix:"OBJETS",brandLogoUrl:"",faviconUrl:"/favicon.svg"};

async function upload(file:FormDataEntryValue|null){if(!(file instanceof File)||!file.size)return null;const body=new FormData();body.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error??"Görsel yüklenemedi.");return String(data.imageUrl);}

export default function BrandEditor(){
  const[values,setValues]=useState(defaults);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(data=>{setValues({...defaults,...data.settings});setMessage("");}).catch(()=>setMessage("Marka ayarları yüklenemedi."));},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");try{const form=new FormData(event.currentTarget);const logo=await upload(form.get("logoFile"));const favicon=await upload(form.get("faviconFile"));const next={brandName:String(form.get("brandName")??""),brandSuffix:String(form.get("brandSuffix")??""),brandLogoUrl:logo??String(form.get("brandLogoUrl")??""),faviconUrl:favicon??String(form.get("faviconUrl")??"")};const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(!response.ok)throw new Error("Marka ayarları kaydedilemedi.");setValues(next);setMessage("Marka kimliği güncellendi.");}catch(error){setMessage(error instanceof Error?error.message:"Marka ayarları kaydedilemedi.");}setBusy(false);}
  return <main className="admin-shell editor-shell"><header className="admin-header"><div><p>MARKA KİMLİĞİ</p><h1>Logo ve isim yönetimi</h1></div><div><a href="/">Ana sayfayı gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card editor-card"><p className="settings-note">Logo hazır değilse isim ve alt isimle devam edin. Daha sonra bir logo yüklediğinizde site otomatik olarak görsel logoya geçer.</p><form className="admin-form" onSubmit={save}><label>Marka adı<input name="brandName" value={values.brandName} onChange={event=>setValues({...values,brandName:event.target.value})} required/></label><label>Alt isim<input name="brandSuffix" value={values.brandSuffix} onChange={event=>setValues({...values,brandSuffix:event.target.value})}/></label><label className="wide">Logo dosyası<input name="logoFile" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"/><small>Şeffaf arka planlı yatay PNG veya WebP önerilir. Boş bırakırsanız yazılı logo kullanılır.</small><input name="brandLogoUrl" value={values.brandLogoUrl} onChange={event=>setValues({...values,brandLogoUrl:event.target.value})} placeholder="Logo bağlantısı"/></label><label className="wide">Tarayıcı simgesi<input name="faviconFile" type="file" accept="image/png,image/svg+xml,image/x-icon"/><small>Kare biçimli 512 × 512 PNG veya SVG önerilir.</small><input name="faviconUrl" value={values.faviconUrl} onChange={event=>setValues({...values,faviconUrl:event.target.value})} placeholder="/favicon.svg"/></label><button disabled={busy}>{busy?"Kaydediliyor…":"Marka kimliğini kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>;
}
