"use client";

import { FormEvent, useEffect, useState } from "react";
import "./orders.css";

type Product = { id:number; nameTr:string; nameEn:string; slug:string; stock:number; priceTr:number; marketTr:boolean; marketGlobal:boolean; active:boolean; imageUrl:string; categoryId:number|null };
type Category = { id:number; nameTr:string; nameEn:string; slug:string; imageUrl:string; parentId:number|null };
type Settings = { brandName:string; brandSuffix:string; announcementTr:string; announcementGlobal:string; heroEyebrow:string; shippingTr:string; freeShippingTr:string; shippingGlobal:string; freeShippingGlobal:string };
type Variant = { id:number; productId:number; sku:string; optionName:string; optionValue:string; optionNameEn:string; optionValueEn:string; stock:number; priceAdjustment:number };
type Order = { id:number; orderNumber:string; status:string; customerName:string; email:string; phone:string; city:string; country:string; subtotal:number; shippingAmount:number; total:number; market:string; createdAt:string };

export default function AdminPanel({ userName }: { userName:string }) {
  const [items,setItems]=useState<Product[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const [categoryItems,setCategoryItems]=useState<Category[]>([]); const [settings,setSettings]=useState<Settings>({brandName:"MYSA",brandSuffix:"OBJETS",announcementTr:"1.500 TL üzeri ücretsiz gönderim",announcementGlobal:"Complimentary shipping over €150",heroEyebrow:"Yavaş yaşam için seçilmiş parçalar",shippingTr:"99",freeShippingTr:"1500",shippingGlobal:"15",freeShippingGlobal:"150"});
  const [variants,setVariants]=useState<Variant[]>([]);
  const [orders,setOrders]=useState<Order[]>([]);
  const load=async()=>{ const [res,categoriesRes,settingsRes,variantsRes,ordersRes]=await Promise.all([fetch("/api/products"),fetch("/api/categories"),fetch("/api/settings"),fetch("/api/variants"),fetch("/api/orders")]); if(res.ok) setItems((await res.json()).products); if(categoriesRes.ok)setCategoryItems((await categoriesRes.json()).categories); if(settingsRes.ok)setSettings((await settingsRes.json()).settings); if(variantsRes.ok)setVariants((await variantsRes.json()).variants); if(ordersRes.ok)setOrders((await ordersRes.json()).orders); };
  useEffect(()=>{ void load(); },[]);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault(); setBusy(true); setMessage(""); const form=new FormData(event.currentTarget);
    let imageUrl=String(form.get("imageUrl")??""); const file=form.get("file");
    if(file instanceof File && file.size){ const upload=new FormData(); upload.set("file",file); const result=await fetch("/api/uploads",{method:"POST",body:upload}); const data=await result.json(); if(!result.ok){setMessage(data.error);setBusy(false);return;} imageUrl=data.imageUrl; }
    const body={nameTr:form.get("nameTr"),nameEn:form.get("nameEn"),slug:form.get("slug"),descriptionTr:form.get("descriptionTr"),descriptionEn:form.get("descriptionEn"),categoryId:form.get("categoryId"),priceTr:form.get("priceTr"),priceGlobal:form.get("priceGlobal"),stock:form.get("stock"),marketTr:form.get("marketTr")==="on",marketGlobal:form.get("marketGlobal")==="on",imageUrl};
    const response=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await response.json();
    setMessage(response.ok?"Ürün kaydedildi.":data.error); if(response.ok){event.currentTarget.reset();await load();} setBusy(false);
  }
  async function remove(id:number){ if(!window.confirm("Bu ürünü silmek istediğinize emin misiniz?"))return; await fetch(`/api/products?id=${id}`,{method:"DELETE"}); await load(); }
  async function updateProduct(item:Product, changes:Partial<Pick<Product,"stock"|"active">>){const response=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,stock:changes.stock??item.stock,active:changes.active??item.active})});setMessage(response.ok?"Ürün güncellendi.":"Ürün güncellenemedi.");if(response.ok)await load();}
  const categoryName=(id:number|null)=>categoryItems.find(category=>category.id===id)?.nameTr??"Kategorisiz";
  async function addCategory(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nameTr:form.get("nameTr"),nameEn:form.get("nameEn"),slug:form.get("slug"),parentId:form.get("parentId"),imageUrl:form.get("imageUrl")})});const data=await response.json();setMessage(response.ok?"Kategori kaydedildi.":data.error);if(response.ok){event.currentTarget.reset();await load();}}
  async function removeCategory(id:number){if(!window.confirm("Kategoriyi silmek istediğinize emin misiniz?"))return;await fetch(`/api/categories?id=${id}`,{method:"DELETE"});await load();}
  async function updateCategoryName(id:number,nameEn:string){const response=await fetch("/api/categories",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,nameEn})});setMessage(response.ok?"Global kategori adı kaydedildi.":"Kategori güncellenemedi.");if(response.ok)await load();}
  async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMessage(response.ok?"Mağaza ayarları güncellendi.":"Ayarlar kaydedilemedi.");if(response.ok)await load();}
  async function addVariant(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/variants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();setMessage(response.ok?"Ürün seçeneği kaydedildi.":data.error);if(response.ok){event.currentTarget.reset();await load();}}
  async function removeVariant(id:number){await fetch(`/api/variants?id=${id}`,{method:"DELETE"});await load();}
  async function updateOrder(id:number,status:string){const response=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});setMessage(response.ok?"Sipariş durumu güncellendi.":"Sipariş güncellenemedi.");if(response.ok)await load();}
  const productName=(id:number)=>items.find(item=>item.id===id)?.nameTr??"Silinmiş ürün";
  return <main className="admin-shell">
    <header className="admin-header"><div><p>MAĞAZA YÖNETİMİ</p><h1>İçerik merkezi</h1></div><div><span>{userName}</span><a href="/">Mağazayı gör ↗</a></div></header>
    <section className="admin-summary"><article><b>{items.length}</b><span>Toplam ürün</span></article><article><b>{items.filter(x=>x.marketTr).length}</b><span>Türkiye</span></article><article><b>{orders.filter(order=>order.status==="new").length}</b><span>Yeni sipariş</span></article><article><b>{items.reduce((a,x)=>a+x.stock,0)}</b><span>Toplam stok</span></article></section>
    <section className="admin-card orders-card"><div className="list-title"><h2>Sipariş talepleri</h2><span>{orders.length} kayıt</span></div>{orders.length===0?<p className="empty">Henüz sipariş talebi yok.</p>:<div className="orders-list">{orders.map(order=><article key={order.id}><div><a className="order-number" href={`/admin/siparis/${order.id}`}>{order.orderNumber} →</a><span>{new Date(order.createdAt).toLocaleDateString("tr-TR")} · {order.market}</span></div><div><strong>{order.customerName}</strong><span>{order.email} · {order.phone}</span><small>{order.city}, {order.country}</small></div><b>{order.market==="TR"?`${order.subtotal.toLocaleString("tr-TR")} TL`:`€${order.subtotal.toLocaleString("en-US")}`}</b><select value={order.status} onChange={event=>updateOrder(order.id,event.target.value)} aria-label={`${order.orderNumber} durumu`}><option value="new">Yeni</option><option value="confirmed">Onaylandı</option><option value="preparing">Hazırlanıyor</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option></select></article>)}</div>}</section>
    <div className="admin-grid"><section className="admin-card"><h2>Yeni ürün</h2><form onSubmit={submit} className="admin-form"><label>Ürün adı · Türkçe<input name="nameTr" required/></label><label>Product name · English<input name="nameEn"/></label><label className="wide">Ürün kodu / adresi<input name="slug" required placeholder="organik-havlu"/></label><label className="wide">Kategori<select name="categoryId" defaultValue=""><option value="">Kategori seçilmedi</option>{categoryItems.map(category=><option key={category.id} value={category.id}>{category.parentId?"— ":""}{category.nameTr}</option>)}</select></label><label className="wide">Açıklama · Türkçe<textarea name="descriptionTr" rows={3}/></label><label className="wide">Description · English<textarea name="descriptionEn" rows={3}/></label><label>Türkiye fiyatı<input name="priceTr" type="number" min="0" step="0.01"/></label><label>Global fiyat (€)<input name="priceGlobal" type="number" min="0" step="0.01"/></label><label>Stok<input name="stock" type="number" min="0" defaultValue="0"/></label><label className="wide">Ürün görseli<input name="file" type="file" accept="image/*"/><small>veya görsel bağlantısı</small><input name="imageUrl" type="url" placeholder="https://..."/></label><div className="checks wide"><label><input name="marketTr" type="checkbox" defaultChecked/> Türkiye</label><label><input name="marketGlobal" type="checkbox"/> Global</label></div><button disabled={busy}>{busy?"Kaydediliyor…":"Ürünü kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section>
    <section className="admin-card product-list"><div className="list-title"><h2>Ürünler</h2><span>{items.length} kayıt</span></div>{items.length===0?<p className="empty">Henüz kayıtlı ürün yok.</p>:items.map(item=><article key={item.id} className={item.active?"":"product-inactive"}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<div className="image-placeholder">Görsel</div>}<div><h3>{item.nameTr}</h3><p>{item.stock} adet · {item.priceTr.toLocaleString("tr-TR")} TL</p><small>{categoryName(item.categoryId)} · {item.marketTr?"TR ":""}{item.marketGlobal?"GLOBAL":""} · {item.active?"Yayında":"Taslak"}</small><div className="stock-controls"><button onClick={()=>updateProduct(item,{stock:Math.max(0,item.stock-1)})} aria-label="Stok azalt">−</button><b>{item.stock}</b><button onClick={()=>updateProduct(item,{stock:item.stock+1})} aria-label="Stok artır">+</button></div></div><div className="product-actions"><a href={`/admin/urun/${item.id}`}>Düzenle</a><button onClick={()=>updateProduct(item,{active:!item.active})}>{item.active?"Yayından kaldır":"Yayınla"}</button><button onClick={()=>remove(item.id)} aria-label={`${item.nameTr} ürününü sil`}>Sil</button></div></article>)}</section></div>
    <div className="admin-grid admin-lower"><section className="admin-card"><h2>Kategoriler</h2><form onSubmit={addCategory} className="admin-form"><label>Kategori adı · Türkçe<input name="nameTr" required placeholder="Banyo & Ev"/></label><label>Category name · English<input name="nameEn" placeholder="Bath & Home"/></label><label>Kategori kodu<input name="slug" required placeholder="banyo-ev"/></label><label>Üst kategori<select name="parentId" defaultValue=""><option value="">Ana kategori</option>{categoryItems.filter(category=>!category.parentId).map(category=><option key={category.id} value={category.id}>{category.nameTr}</option>)}</select></label><label className="wide">Kapak görseli bağlantısı<input name="imageUrl" type="url" placeholder="https://..."/></label><button>Kategori ekle</button></form><div className="category-list">{categoryItems.map(category=><div key={category.id} className={category.parentId?"sub-category":""}><span>{category.parentId?"↳ ":""}{category.nameTr}<small>/{category.slug}</small><input aria-label={`${category.nameTr} İngilizce adı`} defaultValue={category.nameEn} placeholder="Global adı" onBlur={event=>updateCategoryName(category.id,event.target.value)}/></span><div className="category-actions"><a href={`/admin/kategori/${category.id}`}>Düzenle</a><button onClick={()=>removeCategory(category.id)}>Sil</button></div></div>)}</div></section>
    <section className="admin-card"><h2>Mağaza ayarları</h2><p className="settings-note">Marka bilgileriyle Türkiye ve Global teslimat kurallarını buradan yönetebilirsiniz.</p><form onSubmit={saveSettings} className="admin-form"><label>Marka adı<input name="brandName" value={settings.brandName} onChange={e=>setSettings({...settings,brandName:e.target.value})}/></label><label>Alt isim<input name="brandSuffix" value={settings.brandSuffix} onChange={e=>setSettings({...settings,brandSuffix:e.target.value})}/></label><label className="wide">Türkiye duyurusu<input name="announcementTr" value={settings.announcementTr} onChange={e=>setSettings({...settings,announcementTr:e.target.value})}/></label><label className="wide">Global duyuru<input name="announcementGlobal" value={settings.announcementGlobal} onChange={e=>setSettings({...settings,announcementGlobal:e.target.value})}/></label><label className="wide">Ana sayfa üst metni<input name="heroEyebrow" value={settings.heroEyebrow} onChange={e=>setSettings({...settings,heroEyebrow:e.target.value})}/></label><label>Türkiye kargo ücreti (TL)<input name="shippingTr" type="number" min="0" step="0.01" value={settings.shippingTr} onChange={e=>setSettings({...settings,shippingTr:e.target.value})}/></label><label>Türkiye ücretsiz kargo sınırı<input name="freeShippingTr" type="number" min="0" step="0.01" value={settings.freeShippingTr} onChange={e=>setSettings({...settings,freeShippingTr:e.target.value})}/></label><label>Global kargo ücreti (€)<input name="shippingGlobal" type="number" min="0" step="0.01" value={settings.shippingGlobal} onChange={e=>setSettings({...settings,shippingGlobal:e.target.value})}/></label><label>Global ücretsiz kargo sınırı (€)<input name="freeShippingGlobal" type="number" min="0" step="0.01" value={settings.freeShippingGlobal} onChange={e=>setSettings({...settings,freeShippingGlobal:e.target.value})}/></label><button>Ayarları kaydet</button></form></section></div>
    <section className="admin-card variants-card"><div className="list-title"><h2>Ürün seçenekleri</h2><span>{variants.length} seçenek</span></div><form onSubmit={addVariant} className="admin-form variant-form"><label>Ürün<select name="productId" required defaultValue=""><option value="" disabled>Ürün seçin</option>{items.map(item=><option key={item.id} value={item.id}>{item.nameTr}</option>)}</select></label><label>Seçenek türü · Türkçe<select name="optionName" required defaultValue=""><option value="" disabled>Seçin</option><option>Renk</option><option>Beden</option><option>Gramaj</option><option>Paket</option><option>Materyal</option></select></label><label>Seçenek değeri · Türkçe<input name="optionValue" required placeholder="Bej, XL, 2 kg..."/></label><label>Option type · English<input name="optionNameEn" placeholder="Color, Size, Weight..."/></label><label>Option value · English<input name="optionValueEn" placeholder="Beige, XL, 2 kg..."/></label><label>Ürün kodu (SKU)<input name="sku" required placeholder="HV-BEJ-XL"/></label><label>Stok<input name="stock" type="number" min="0" defaultValue="0"/></label><label>Fiyat farkı<input name="priceAdjustment" type="number" step="0.01" defaultValue="0"/></label><button>Seçenek ekle</button></form><div className="variant-list">{variants.map(variant=><article key={variant.id}><div><b>{productName(variant.productId)}</b><span>{variant.optionName}: {variant.optionValue}{variant.optionValueEn?` · ${variant.optionNameEn||variant.optionName}: ${variant.optionValueEn}`:""} · {variant.stock} adet · {variant.priceAdjustment?`${variant.priceAdjustment>0?"+":""}${variant.priceAdjustment} fiyat farkı`:"Standart fiyat"}</span></div><code>{variant.sku}</code><button onClick={()=>removeVariant(variant.id)}>Sil</button></article>)}</div></section>
  </main>;
}
