"use client";

import { FormEvent, useEffect, useState } from "react";
import "./orders.css";
import "./contact-inbox.css";
import "./policy-editor.css";

type Product = { id:number; nameTr:string; nameEn:string; slug:string; stock:number; priceTr:number; marketTr:boolean; marketGlobal:boolean; active:boolean; imageUrl:string; categoryId:number|null };
type Category = { id:number; nameTr:string; nameEn:string; slug:string; imageUrl:string; parentId:number|null };
type Settings = { brandName:string; brandSuffix:string; announcementTr:string; announcementGlobal:string; heroEyebrow:string; heroTitle:string; heroTitleAccent:string; heroCopy:string; heroButton:string; heroImageUrl:string; introTitle:string; introCopy:string; shippingTr:string; freeShippingTr:string; shippingGlobal:string; freeShippingGlobal:string; shippingPolicyTr:string; returnsPolicyTr:string; shippingPolicyGlobal:string; returnsPolicyGlobal:string; privacyPolicy:string };
type Variant = { id:number; productId:number; sku:string; optionName:string; optionValue:string; optionNameEn:string; optionValueEn:string; stock:number; priceAdjustment:number };
type Order = { id:number; orderNumber:string; status:string; customerName:string; email:string; phone:string; city:string; country:string; subtotal:number; shippingAmount:number; total:number; market:string; createdAt:string };
type ContactMessage = { id:number; name:string; email:string; orderNumber:string; subject:string; message:string; status:string; createdAt:string };

export default function AdminPanel({ userName }: { userName:string }) {
  const [items,setItems]=useState<Product[]>([]); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const [categoryItems,setCategoryItems]=useState<Category[]>([]); const [settings,setSettings]=useState<Settings>({brandName:"MYSA",brandSuffix:"OBJETS",announcementTr:"1.500 TL üzeri ücretsiz gönderim",announcementGlobal:"Complimentary shipping over €150",heroEyebrow:"Yavaş yaşam için seçilmiş parçalar",heroTitle:"Gündelik olanı",heroTitleAccent:"olağanüstü kılın.",heroCopy:"Eviniz, gardırobunuz ve en yakın dostlarınız için; dokusu, işçiliği ve hikâyesi olan zamansız objeler.",heroButton:"Yeni seçkiyi keşfet",heroImageUrl:"https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=2000&q=90",introTitle:"Daha az, ama daha iyi.",introCopy:"Dokunmak isteyeceğiniz tekstillerden bilinçli üretilmiş aksesuarlara ve dostlarımız için özenle seçilmiş ürünlere uzanan modern bir yaşam koleksiyonu.",shippingTr:"99",freeShippingTr:"1500",shippingGlobal:"15",freeShippingGlobal:"150",shippingPolicyTr:"Sipariş talepleri onaylandıktan sonra hazırlanır. Teslimat süresi ürün ve teslimat adresine göre paylaşılır.",returnsPolicyTr:"İade veya değişim talebiniz için sipariş numaranızla bize ulaşın.",shippingPolicyGlobal:"Global order requests are reviewed before preparation. Delivery timing is confirmed according to destination.",returnsPolicyGlobal:"For a return or exchange request, contact us with your order number.",privacyPolicy:"Paylaştığınız bilgiler sipariş ve iletişim taleplerinizi işlemek amacıyla kaydedilir."});
  const [variants,setVariants]=useState<Variant[]>([]);
  const [orders,setOrders]=useState<Order[]>([]);
  const [contactMessages,setContactMessages]=useState<ContactMessage[]>([]);
  const [orderFilter,setOrderFilter]=useState("active");
  const [homepageBusy,setHomepageBusy]=useState(false);
  const load=async()=>{ const [res,categoriesRes,settingsRes,variantsRes,ordersRes,contactRes]=await Promise.all([fetch("/api/products"),fetch("/api/categories"),fetch("/api/settings"),fetch("/api/variants"),fetch("/api/orders"),fetch("/api/contact")]); if(res.ok) setItems((await res.json()).products); if(categoriesRes.ok)setCategoryItems((await categoriesRes.json()).categories); if(settingsRes.ok)setSettings((await settingsRes.json()).settings); if(variantsRes.ok)setVariants((await variantsRes.json()).variants); if(ordersRes.ok)setOrders((await ordersRes.json()).orders);if(contactRes.ok)setContactMessages((await contactRes.json()).messages); };
  useEffect(()=>{ void load(); },[]);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault(); setBusy(true); setMessage(""); const form=new FormData(event.currentTarget);
    let imageUrl=String(form.get("imageUrl")??""); const file=form.get("file");
    if(file instanceof File && file.size){ const upload=new FormData(); upload.set("file",file); const result=await fetch("/api/uploads",{method:"POST",body:upload}); const data=await result.json(); if(!result.ok){setMessage(data.error);setBusy(false);return;} imageUrl=data.imageUrl; }
    const body={nameTr:form.get("nameTr"),nameEn:form.get("nameEn"),slug:form.get("slug"),descriptionTr:form.get("descriptionTr"),descriptionEn:form.get("descriptionEn"),categoryId:form.get("categoryId"),priceTr:form.get("priceTr"),priceGlobal:form.get("priceGlobal"),stock:form.get("stock"),marketTr:form.get("marketTr")==="on",marketGlobal:form.get("marketGlobal")==="on",imageUrl};
    const response=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const data=await response.json();
    setMessage(response.ok?"Ürün kaydedildi.":data.error); if(response.ok){event.currentTarget.reset();await load();} setBusy(false);
  }
  async function remove(id:number){ if(!window.confirm("Bu ürünü silmek istediğinize emin misiniz?"))return; await fetch(`/api/products?id=${id}`,{method:"DELETE"}); await load(); }
  async function updateProduct(item:Product, changes:Partial<Pick<Product,"stock"|"active">>){const response=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,stock:changes.stock??item.stock,active:changes.active??item.active})});setMessage(response.ok?"Ürün güncellendi.":"Ürün güncellenemedi.");if(response.ok)await load();}
  const categoryName=(id:number|null)=>categoryItems.find(category=>category.id===id)?.nameTr??"Kategorisiz";
  async function addCategory(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({nameTr:form.get("nameTr"),nameEn:form.get("nameEn"),slug:form.get("slug"),parentId:form.get("parentId"),imageUrl:form.get("imageUrl")})});const data=await response.json();setMessage(response.ok?"Kategori kaydedildi.":data.error);if(response.ok){event.currentTarget.reset();await load();}}
  async function removeCategory(id:number){if(!window.confirm("Kategoriyi silmek istediğinize emin misiniz?"))return;await fetch(`/api/categories?id=${id}`,{method:"DELETE"});await load();}
  async function updateCategoryName(id:number,nameEn:string){const response=await fetch("/api/categories",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,nameEn})});setMessage(response.ok?"Global kategori adı kaydedildi.":"Kategori güncellenemedi.");if(response.ok)await load();}
  async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMessage(response.ok?"Mağaza ayarları güncellendi.":"Ayarlar kaydedilemedi.");if(response.ok)await load();}
  async function savePolicies(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMessage(response.ok?"Bilgilendirme metinleri güncellendi.":"Metinler kaydedilemedi.");if(response.ok)await load();}
  async function saveHomepage(event:FormEvent<HTMLFormElement>){event.preventDefault();setHomepageBusy(true);setMessage("");const form=new FormData(event.currentTarget);let heroImageUrl=String(form.get("heroImageUrl")??settings.heroImageUrl);const file=form.get("heroFile");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const uploadResponse=await fetch("/api/uploads",{method:"POST",body:upload});const uploadData=await uploadResponse.json();if(!uploadResponse.ok){setMessage(uploadData.error??"Kapak görseli yüklenemedi.");setHomepageBusy(false);return;}heroImageUrl=uploadData.imageUrl;}const body={heroEyebrow:form.get("heroEyebrow"),heroTitle:form.get("heroTitle"),heroTitleAccent:form.get("heroTitleAccent"),heroCopy:form.get("heroCopy"),heroButton:form.get("heroButton"),heroImageUrl,introTitle:form.get("introTitle"),introCopy:form.get("introCopy")};const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(response.ok?"Ana sayfa vitrini güncellendi.":"Vitrin ayarları kaydedilemedi.");if(response.ok)await load();setHomepageBusy(false);}
  async function addVariant(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/variants",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const data=await response.json();setMessage(response.ok?"Ürün seçeneği kaydedildi.":data.error);if(response.ok){event.currentTarget.reset();await load();}}
  async function removeVariant(id:number){await fetch(`/api/variants?id=${id}`,{method:"DELETE"});await load();}
  async function updateOrder(id:number,status:string){const response=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});setMessage(response.ok?"Sipariş durumu güncellendi.":"Sipariş güncellenemedi.");if(response.ok)await load();}
  async function updateContact(id:number,status:string){const response=await fetch("/api/contact",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});setMessage(response.ok?"Mesaj durumu güncellendi.":"Mesaj güncellenemedi.");if(response.ok)await load();}
  const productName=(id:number)=>items.find(item=>item.id===id)?.nameTr??"Silinmiş ürün";
  const activeOrders=orders.filter(order=>order.status!=="completed"&&order.status!=="cancelled");
  const visibleOrders=(orderFilter==="all"?orders:orderFilter==="active"?activeOrders:orders.filter(order=>order.status===orderFilter)).slice(0,12);
  const lowStock=[
    ...items.filter(item=>item.active&&item.stock<=5&&!variants.some(variant=>variant.productId===item.id)).map(item=>({key:`p-${item.id}`,name:item.nameTr,detail:"Ana stok",stock:item.stock,href:`/admin/urun/${item.id}`})),
    ...variants.filter(variant=>variant.stock<=5).map(variant=>({key:`v-${variant.id}`,name:productName(variant.productId),detail:`${variant.optionName}: ${variant.optionValue}`,stock:variant.stock,href:`/admin/varyant/${variant.id}`})),
  ].sort((a,b)=>a.stock-b.stock);
  const confirmedOrders=orders.filter(order=>["confirmed","preparing","completed"].includes(order.status));
  const trDemand=confirmedOrders.filter(order=>order.market==="TR").reduce((sum,order)=>sum+order.total,0);
  const globalDemand=confirmedOrders.filter(order=>order.market==="GLOBAL").reduce((sum,order)=>sum+order.total,0);
  const today=new Date().toLocaleDateString("en-CA");
  const todayOrders=orders.filter(order=>new Date(order.createdAt).toLocaleDateString("en-CA")===today);
  return <main className="admin-shell">
    <header className="admin-header"><div><p>MAĞAZA YÖNETİMİ</p><h1>İçerik merkezi</h1></div><div><span>{userName}</span><a href="/">Mağazayı gör ↗</a></div></header>
    <section className="admin-summary"><article><b>{orders.filter(order=>order.status==="new").length}</b><span>Yeni sipariş</span></article><article><b>{contactMessages.filter(item=>item.status==="new").length}</b><span>Yeni mesaj</span></article><article className={lowStock.length?"summary-warning":""}><b>{lowStock.length}</b><span>Kritik stok</span></article><article><b>{items.filter(item=>item.active).length}</b><span>Yayındaki ürün</span></article></section>
    <section className="dashboard-grid">
      <article className="admin-card stock-watch"><div className="list-title"><div><p className="section-kicker">STOK TAKİBİ</p><h2>Dikkat gerekenler</h2></div><span>5 ve altı</span></div>{lowStock.length===0?<p className="healthy-state">Tüm ürünlerin stok seviyesi iyi görünüyor.</p>:<div className="stock-watch-list">{lowStock.slice(0,8).map(item=><a key={item.key} href={item.href}><span><b>{item.name}</b><small>{item.detail}</small></span><strong className={item.stock===0?"out":""}>{item.stock===0?"Tükendi":`${item.stock} adet`} →</strong></a>)}</div>}</article>
      <article className="admin-card daily-view"><p className="section-kicker">BUGÜNÜN GÖRÜNÜMÜ</p><h2>Mağaza özeti</h2><div className="daily-metrics"><div><b>{todayOrders.length}</b><span>Bugün gelen</span></div><div><b>{orders.filter(order=>order.status==="preparing").length}</b><span>Hazırlanan</span></div><div><b>{orders.filter(order=>order.status==="completed").length}</b><span>Tamamlanan</span></div></div><div className="demand-total"><span>Onaylanan talep değeri</span><p><b>{trDemand.toLocaleString("tr-TR")} TL</b><b>€{globalDemand.toLocaleString("en-US")}</b></p></div><nav className="quick-links"><a href="#homepage-editor">Ana vitrini düzenle</a><a href="#new-product">+ Ürün ekle</a><a href="#categories">+ Kategori ekle</a><a href="#store-settings">Mağaza ayarları</a></nav></article>
    </section>
    <section className="admin-card homepage-editor" id="homepage-editor"><div className="list-title"><div><p className="section-kicker">ANA SAYFA</p><h2>Vitrin yönetimi</h2></div><a href="/" target="_blank" rel="noreferrer">Canlı vitrini aç ↗</a></div><div className="homepage-editor-grid"><form className="admin-form" onSubmit={saveHomepage}><label className="wide">Kapak üst metni<input name="heroEyebrow" value={settings.heroEyebrow} onChange={event=>setSettings({...settings,heroEyebrow:event.target.value})}/></label><label>Ana başlık<input name="heroTitle" value={settings.heroTitle} onChange={event=>setSettings({...settings,heroTitle:event.target.value})}/></label><label>Vurgulu başlık<input name="heroTitleAccent" value={settings.heroTitleAccent} onChange={event=>setSettings({...settings,heroTitleAccent:event.target.value})}/></label><label className="wide">Kapak açıklaması<textarea name="heroCopy" rows={3} value={settings.heroCopy} onChange={event=>setSettings({...settings,heroCopy:event.target.value})}/></label><label className="wide">Buton yazısı<input name="heroButton" value={settings.heroButton} onChange={event=>setSettings({...settings,heroButton:event.target.value})}/></label><label className="wide">Yeni kapak fotoğrafı<input name="heroFile" type="file" accept="image/*"/><small>Yeni dosya seçmezseniz mevcut görsel korunur.</small><input name="heroImageUrl" value={settings.heroImageUrl} onChange={event=>setSettings({...settings,heroImageUrl:event.target.value})} placeholder="Görsel bağlantısı"/></label><label className="wide">Tanıtım başlığı<input name="introTitle" value={settings.introTitle} onChange={event=>setSettings({...settings,introTitle:event.target.value})}/></label><label className="wide">Tanıtım açıklaması<textarea name="introCopy" rows={4} value={settings.introCopy} onChange={event=>setSettings({...settings,introCopy:event.target.value})}/></label><button disabled={homepageBusy}>{homepageBusy?"Kaydediliyor…":"Vitrini kaydet"}</button></form><aside className="homepage-preview" style={{backgroundImage:`linear-gradient(90deg,rgba(22,29,23,.75),rgba(22,29,23,.12)),url("${settings.heroImageUrl.replaceAll('"','%22')}")`}}><span>CANLI ÖNİZLEME</span><div><small>{settings.heroEyebrow}</small><h3>{settings.heroTitle}<em>{settings.heroTitleAccent}</em></h3><p>{settings.heroCopy}</p><b>{settings.heroButton} →</b></div></aside></div>{message&&<p className="admin-message">{message}</p>}</section>
    <section className="admin-card orders-card"><div className="list-title"><div><p className="section-kicker">SİPARİŞ YÖNETİMİ</p><h2>Sipariş talepleri</h2></div><span>{visibleOrders.length} / {orders.length} kayıt</span></div><div className="order-filters" aria-label="Siparişleri filtrele">{[["active","Aktif"],["new","Yeni"],["confirmed","Onaylandı"],["preparing","Hazırlanıyor"],["completed","Tamamlandı"],["cancelled","İptal"],["all","Tümü"]].map(([value,label])=><button key={value} className={orderFilter===value?"active":""} onClick={()=>setOrderFilter(value)}>{label}</button>)}</div>{visibleOrders.length===0?<p className="empty">Bu durumda sipariş talebi yok.</p>:<div className="orders-list">{visibleOrders.map(order=><article key={order.id}><div><a className="order-number" href={`/admin/siparis/${order.id}`}>{order.orderNumber} →</a><span>{new Date(order.createdAt).toLocaleDateString("tr-TR")} · {order.market}</span></div><div><strong>{order.customerName}</strong><span>{order.email} · {order.phone}</span><small>{order.city}, {order.country}</small></div><b>{order.market==="TR"?`${order.total.toLocaleString("tr-TR")} TL`:`€${order.total.toLocaleString("en-US")}`}</b><select value={order.status} onChange={event=>updateOrder(order.id,event.target.value)} aria-label={`${order.orderNumber} durumu`}><option value="new">Yeni</option><option value="confirmed">Onaylandı</option><option value="preparing">Hazırlanıyor</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option></select></article>)}</div>}</section>
    <section className="admin-card contact-inbox"><div className="list-title"><div><p className="section-kicker">MÜŞTERİ DESTEĞİ</p><h2>Gelen mesajlar</h2></div><span>{contactMessages.filter(item=>item.status!=="resolved").length} açık mesaj</span></div>{contactMessages.length===0?<p className="empty">Henüz müşteri mesajı yok.</p>:<div className="contact-inbox-list">{contactMessages.slice(0,12).map(item=><article key={item.id} className={item.status==="new"?"new-message":""}><header><div><b>{item.subject}</b><span>{item.name} · {new Date(item.createdAt).toLocaleDateString("tr-TR")}</span></div><select value={item.status} onChange={event=>updateContact(item.id,event.target.value)} aria-label={`${item.name} mesaj durumu`}><option value="new">Yeni</option><option value="read">Okundu</option><option value="resolved">Çözüldü</option></select></header><p>{item.message}</p><footer><a href={`mailto:${item.email}?subject=${encodeURIComponent(`RE: ${item.subject}${item.orderNumber?` · ${item.orderNumber}`:""}`)}`}>{item.email} →</a>{item.orderNumber&&<a href={`/siparis-takip?order=${encodeURIComponent(item.orderNumber)}`}>{item.orderNumber}</a>}</footer></article>)}</div>}</section>
    <div className="admin-grid"><section className="admin-card" id="new-product"><h2>Yeni ürün</h2><form onSubmit={submit} className="admin-form"><label>Ürün adı · Türkçe<input name="nameTr" required/></label><label>Product name · English<input name="nameEn"/></label><label className="wide">Ürün kodu / adresi<input name="slug" required placeholder="organik-havlu"/></label><label className="wide">Kategori<select name="categoryId" defaultValue=""><option value="">Kategori seçilmedi</option>{categoryItems.map(category=><option key={category.id} value={category.id}>{category.parentId?"— ":""}{category.nameTr}</option>)}</select></label><label className="wide">Açıklama · Türkçe<textarea name="descriptionTr" rows={3}/></label><label className="wide">Description · English<textarea name="descriptionEn" rows={3}/></label><label>Türkiye fiyatı<input name="priceTr" type="number" min="0" step="0.01"/></label><label>Global fiyat (€)<input name="priceGlobal" type="number" min="0" step="0.01"/></label><label>Stok<input name="stock" type="number" min="0" defaultValue="0"/></label><label className="wide">Ürün görseli<input name="file" type="file" accept="image/*"/><small>veya görsel bağlantısı</small><input name="imageUrl" type="url" placeholder="https://..."/></label><div className="checks wide"><label><input name="marketTr" type="checkbox" defaultChecked/> Türkiye</label><label><input name="marketGlobal" type="checkbox"/> Global</label></div><button disabled={busy}>{busy?"Kaydediliyor…":"Ürünü kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section>
    <section className="admin-card product-list"><div className="list-title"><h2>Ürünler</h2><span>{items.length} kayıt</span></div>{items.length===0?<p className="empty">Henüz kayıtlı ürün yok.</p>:items.map(item=><article key={item.id} className={item.active?"":"product-inactive"}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<div className="image-placeholder">Görsel</div>}<div><h3>{item.nameTr}</h3><p>{item.stock} adet · {item.priceTr.toLocaleString("tr-TR")} TL</p><small>{categoryName(item.categoryId)} · {item.marketTr?"TR ":""}{item.marketGlobal?"GLOBAL":""} · {item.active?"Yayında":"Taslak"}</small><div className="stock-controls"><button onClick={()=>updateProduct(item,{stock:Math.max(0,item.stock-1)})} aria-label="Stok azalt">−</button><b>{item.stock}</b><button onClick={()=>updateProduct(item,{stock:item.stock+1})} aria-label="Stok artır">+</button></div></div><div className="product-actions"><a href={`/admin/urun/${item.id}`}>Düzenle</a><button onClick={()=>updateProduct(item,{active:!item.active})}>{item.active?"Yayından kaldır":"Yayınla"}</button><button onClick={()=>remove(item.id)} aria-label={`${item.nameTr} ürününü sil`}>Sil</button></div></article>)}</section></div>
    <div className="admin-grid admin-lower"><section className="admin-card" id="categories"><h2>Kategoriler</h2><form onSubmit={addCategory} className="admin-form"><label>Kategori adı · Türkçe<input name="nameTr" required placeholder="Banyo & Ev"/></label><label>Category name · English<input name="nameEn" placeholder="Bath & Home"/></label><label>Kategori kodu<input name="slug" required placeholder="banyo-ev"/></label><label>Üst kategori<select name="parentId" defaultValue=""><option value="">Ana kategori</option>{categoryItems.filter(category=>!category.parentId).map(category=><option key={category.id} value={category.id}>{category.nameTr}</option>)}</select></label><label className="wide">Kapak görseli bağlantısı<input name="imageUrl" type="url" placeholder="https://..."/></label><button>Kategori ekle</button></form><div className="category-list">{categoryItems.map(category=><div key={category.id} className={category.parentId?"sub-category":""}><span>{category.parentId?"↳ ":""}{category.nameTr}<small>/{category.slug}</small><input aria-label={`${category.nameTr} İngilizce adı`} defaultValue={category.nameEn} placeholder="Global adı" onBlur={event=>updateCategoryName(category.id,event.target.value)}/></span><div className="category-actions"><a href={`/admin/kategori/${category.id}`}>Düzenle</a><button onClick={()=>removeCategory(category.id)}>Sil</button></div></div>)}</div></section>
    <section className="admin-card" id="store-settings"><h2>Mağaza ayarları</h2><p className="settings-note">Marka bilgileriyle Türkiye ve Global teslimat kurallarını buradan yönetebilirsiniz.</p><form onSubmit={saveSettings} className="admin-form"><label>Marka adı<input name="brandName" value={settings.brandName} onChange={e=>setSettings({...settings,brandName:e.target.value})}/></label><label>Alt isim<input name="brandSuffix" value={settings.brandSuffix} onChange={e=>setSettings({...settings,brandSuffix:e.target.value})}/></label><label className="wide">Türkiye duyurusu<input name="announcementTr" value={settings.announcementTr} onChange={e=>setSettings({...settings,announcementTr:e.target.value})}/></label><label className="wide">Global duyuru<input name="announcementGlobal" value={settings.announcementGlobal} onChange={e=>setSettings({...settings,announcementGlobal:e.target.value})}/></label><label className="wide">Ana sayfa üst metni<input name="heroEyebrow" value={settings.heroEyebrow} onChange={e=>setSettings({...settings,heroEyebrow:e.target.value})}/></label><label>Türkiye kargo ücreti (TL)<input name="shippingTr" type="number" min="0" step="0.01" value={settings.shippingTr} onChange={e=>setSettings({...settings,shippingTr:e.target.value})}/></label><label>Türkiye ücretsiz kargo sınırı<input name="freeShippingTr" type="number" min="0" step="0.01" value={settings.freeShippingTr} onChange={e=>setSettings({...settings,freeShippingTr:e.target.value})}/></label><label>Global kargo ücreti (€)<input name="shippingGlobal" type="number" min="0" step="0.01" value={settings.shippingGlobal} onChange={e=>setSettings({...settings,shippingGlobal:e.target.value})}/></label><label>Global ücretsiz kargo sınırı (€)<input name="freeShippingGlobal" type="number" min="0" step="0.01" value={settings.freeShippingGlobal} onChange={e=>setSettings({...settings,freeShippingGlobal:e.target.value})}/></label><button>Ayarları kaydet</button></form></section></div>
    <section className="admin-card policy-editor" id="policy-editor"><div className="list-title"><div><p className="section-kicker">SATIŞ BİLGİLERİ</p><h2>Politika içerikleri</h2></div><a href="/politikalar" target="_blank" rel="noreferrer">Sayfayı aç ↗</a></div><p className="settings-note">Bu metinler operasyonel taslaktır. İşletme bilgileriniz kesinleştiğinde nihai hukuki metinleri uzmanınızla gözden geçirebilirsiniz.</p><form onSubmit={savePolicies} className="admin-form policy-form"><label>Türkiye teslimat<textarea name="shippingPolicyTr" rows={5} value={settings.shippingPolicyTr} onChange={event=>setSettings({...settings,shippingPolicyTr:event.target.value})}/></label><label>Türkiye iade ve değişim<textarea name="returnsPolicyTr" rows={5} value={settings.returnsPolicyTr} onChange={event=>setSettings({...settings,returnsPolicyTr:event.target.value})}/></label><label>Global shipping<textarea name="shippingPolicyGlobal" rows={5} value={settings.shippingPolicyGlobal} onChange={event=>setSettings({...settings,shippingPolicyGlobal:event.target.value})}/></label><label>Global returns & exchanges<textarea name="returnsPolicyGlobal" rows={5} value={settings.returnsPolicyGlobal} onChange={event=>setSettings({...settings,returnsPolicyGlobal:event.target.value})}/></label><label className="wide">Gizlilik açıklaması<textarea name="privacyPolicy" rows={6} value={settings.privacyPolicy} onChange={event=>setSettings({...settings,privacyPolicy:event.target.value})}/></label><button>Metinleri kaydet</button></form></section>
    <section className="admin-card variants-card"><div className="list-title"><h2>Ürün seçenekleri</h2><span>{variants.length} seçenek</span></div><form onSubmit={addVariant} className="admin-form variant-form"><label>Ürün<select name="productId" required defaultValue=""><option value="" disabled>Ürün seçin</option>{items.map(item=><option key={item.id} value={item.id}>{item.nameTr}</option>)}</select></label><label>Seçenek türü · Türkçe<select name="optionName" required defaultValue=""><option value="" disabled>Seçin</option><option>Renk</option><option>Beden</option><option>Gramaj</option><option>Paket</option><option>Materyal</option></select></label><label>Seçenek değeri · Türkçe<input name="optionValue" required placeholder="Bej, XL, 2 kg..."/></label><label>Option type · English<input name="optionNameEn" placeholder="Color, Size, Weight..."/></label><label>Option value · English<input name="optionValueEn" placeholder="Beige, XL, 2 kg..."/></label><label>Ürün kodu (SKU)<input name="sku" required placeholder="HV-BEJ-XL"/></label><label>Stok<input name="stock" type="number" min="0" defaultValue="0"/></label><label>Fiyat farkı<input name="priceAdjustment" type="number" step="0.01" defaultValue="0"/></label><button>Seçenek ekle</button></form><div className="variant-list">{variants.map(variant=><article key={variant.id}><div><b>{productName(variant.productId)}</b><span>{variant.optionName}: {variant.optionValue}{variant.optionValueEn?` · ${variant.optionNameEn||variant.optionName}: ${variant.optionValueEn}`:""} · {variant.stock} adet · {variant.priceAdjustment?`${variant.priceAdjustment>0?"+":""}${variant.priceAdjustment} fiyat farkı`:"Standart fiyat"}</span></div><code>{variant.sku}</code><div className="variant-actions"><a href={`/admin/varyant/${variant.id}`}>Düzenle</a><button onClick={()=>removeVariant(variant.id)}>Sil</button></div></article>)}</div></section>
  </main>;
}
