"use client";

import{useEffect,useMemo,useState}from"react";

type Item={id:number;name:string;slug:string;active:boolean;featured:boolean;marketTr:boolean;marketGlobal:boolean;category:string;updatedAt:string;blockers:string[];warnings:string[];score:number;ready:boolean;sellableStock:number;imageCount:number};
type Data={generatedAt:string;summary:{total:number;active:number;draft:number;ready:number;blocked:number;warnings:number};items:Item[]};

export default function CatalogQualityCenter(){
  const[data,setData]=useState<Data|null>(null);const[message,setMessage]=useState("Katalog inceleniyor…");const[filter,setFilter]=useState("blocked");const[query,setQuery]=useState("");
  const load=async()=>{const response=await fetch("/api/catalog-quality");const result=await response.json();if(response.ok){setData(result);setMessage("");}else setMessage(result.error??"Katalog denetimi yüklenemedi.");};
  useEffect(()=>{void load();},[]);
  const visible=useMemo(()=>{if(!data)return[];const needle=query.trim().toLocaleLowerCase("tr-TR");return data.items.filter(item=>(filter==="all"||filter==="blocked"&&!item.ready||filter==="ready"&&item.ready||filter==="warnings"&&item.warnings.length>0||filter==="active"&&item.active||filter==="draft"&&!item.active)&&(!needle||`${item.name} ${item.slug} ${item.category}`.toLocaleLowerCase("tr-TR").includes(needle)));},[data,filter,query]);
  return <main className="admin-shell catalog-quality-shell"><header className="admin-header"><div><p>ÜRÜN KALİTESİ</p><h1>Katalog kalite merkezi</h1></div><div><button className="quality-refresh" onClick={load}>Yeniden denetle</button><a href="/admin">Panele dön ↗</a><a href="/admin/toplu-urun">CSV aktarımı ↗</a></div></header>
    {!data?<section className="admin-card quality-loading">{message}</section>:<><section className="quality-summary"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}><b>{data.summary.total}</b><span>Toplam ürün</span></button><button className={filter==="blocked"?"active danger":"danger"} onClick={()=>setFilter("blocked")}><b>{data.summary.blocked}</b><span>Yayın engelli</span></button><button className={filter==="ready"?"active ready":"ready"} onClick={()=>setFilter("ready")}><b>{data.summary.ready}</b><span>Yayına hazır</span></button><button className={filter==="warnings"?"active warning":"warning"} onClick={()=>setFilter("warnings")}><b>{data.summary.warnings}</b><span>İyileştirme uyarısı</span></button><button className={filter==="draft"?"active":""} onClick={()=>setFilter("draft")}><b>{data.summary.draft}</b><span>Taslak</span></button></section>
      <section className="admin-card quality-list"><div className="quality-toolbar"><div><p className="section-kicker">DENETİM SONUCU</p><h2>{visible.length} ürün gösteriliyor</h2></div><label><span className="sr-only">Ürün ara</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ürün, kod veya kategori ara…"/></label></div>
        {visible.length===0?<p className="healthy-state">Bu filtrede ürün bulunmuyor.</p>:visible.map(item=><article className={item.ready?"quality-item ready":"quality-item blocked"} key={item.id}><div className="quality-score"><b>{item.score}</b><span>/ 100</span></div><div className="quality-copy"><header><div><h3>{item.name}</h3><p>{item.category} · /{item.slug}</p></div><span>{item.active?"Yayında":"Taslak"}</span></header><div className="quality-facts"><span>{item.marketTr?"TR ✓":"TR —"}</span><span>{item.marketGlobal?"Global ✓":"Global —"}</span><span>{item.sellableStock} stok</span><span>{item.imageCount} görsel</span>{item.featured&&<span>Vitrinde</span>}</div>{item.blockers.length>0&&<div className="quality-issues blockers"><b>Yayın engelleri</b>{item.blockers.map(issue=><span key={issue}>! {issue}</span>)}</div>}{item.warnings.length>0&&<div className="quality-issues warnings"><b>İyileştirme önerileri</b>{item.warnings.map(issue=><span key={issue}>• {issue}</span>)}</div>}{item.ready&&!item.warnings.length&&<p className="quality-perfect">Yayın için zorunlu ve önerilen alanlar tamam.</p>}</div><a className="quality-edit" href={`/admin/urun/${item.id}`}>Ürünü düzenle →</a></article>)}</section></>}
  </main>;
}
