import { asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { categories } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

export const dynamic = "force-dynamic";
export async function GET() { try { return Response.json({ categories: await getDb().select().from(categories).orderBy(asc(categories.sortOrder), asc(categories.id)) }); } catch { return Response.json({ categories: [] }); } }
export async function POST(request: Request) { if (!(await getChatGPTUser())) return Response.json({ error: "Yetkisiz erişim" }, { status: 401 }); const body = await request.json() as Record<string, unknown>; const nameTr = String(body.nameTr ?? "").trim(); const slug = String(body.slug ?? "").trim(); if (!nameTr || !slug) return Response.json({ error: "Kategori adı ve kodu zorunludur." }, { status: 400 }); const [category] = await getDb().insert(categories).values({ nameTr, nameEn:String(body.nameEn??"").trim(), slug, parentId: Number(body.parentId) || null, imageUrl: String(body.imageUrl ?? ""), sortOrder: Number(body.sortOrder ?? 0) }).returning(); return Response.json({ category }, { status: 201 }); }
export async function PATCH(request: Request) { if (!(await getChatGPTUser())) return Response.json({ error:"Yetkisiz erişim" },{status:401}); const body=await request.json() as Record<string,unknown>;const id=Number(body.id);if(!id)return Response.json({error:"Geçersiz kategori"},{status:400});const updates:Partial<typeof categories.$inferInsert>={};if(body.nameTr!==undefined)updates.nameTr=String(body.nameTr).trim();if(body.nameEn!==undefined)updates.nameEn=String(body.nameEn).trim();if(body.slug!==undefined)updates.slug=String(body.slug).trim();if(body.parentId!==undefined)updates.parentId=Number(body.parentId)||null;if(body.imageUrl!==undefined)updates.imageUrl=String(body.imageUrl);if(body.sortOrder!==undefined)updates.sortOrder=Number(body.sortOrder)||0;if(body.active!==undefined)updates.active=Boolean(body.active);const[category]=await getDb().update(categories).set(updates).where(eq(categories.id,id)).returning();return Response.json({category}); }
export async function DELETE(request: Request) { if (!(await getChatGPTUser())) return Response.json({ error: "Yetkisiz erişim" }, { status: 401 }); const id = Number(new URL(request.url).searchParams.get("id")); if (!id) return Response.json({ error: "Geçersiz kategori" }, { status: 400 }); await getDb().delete(categories).where(eq(categories.id, id)); return Response.json({ ok: true }); }
