"use client";

import {FormEvent,useEffect,useState} from "react";

type Values={seoTitle:string;seoDescription:string;seoKeywords:string;seoImageUrl:string};
const defaults:Values={seoTitle:"MYSA OBJETS — Seçkili Yaşam Ürünleri",seoDescription:"Eviniz, gardırobunuz ve dostlarınız için zamansız, özenle seçilmiş yaşam ürünleri.",seoKeywords:"seçkili yaşam ürünleri, tekstil, ev, aksesuar, pet",seoImageUrl:"/og.png"};

export default function SeoEditor(){
  const[values,setValues]=useState(defaults);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(data=>{setValues({...defaults,...data.settings});setMessage("");}).catch(()=>setMessage("SEO ayarları yüklenemedi."));},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);let seoImageUrl=String(form.get("seoImageUrl")??values.seoImageUrl);const file=form.get("seoFile");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const uploadResponse=await fetch("/api/uploads",{method:"POST",body:upload});const uploadData=await uploadResponse.json();if(!uploadResponse.ok){setMessage(uploadData.error??"Paylaşım görseli yüklenemedi.");setBusy(false);return;}seoImageUrl=uploadData.imageUrl;}const next={seoTitle:String(form.get("seoTitle")??""),seoDescription:String(form.get("seoDescription")??""),seoKeywords:String(form.get("seoKeywords")??""),seoImageUrl};const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(response.ok){setValues(next);setMessage("SEO ayarları güncellendi.");}else setMessage("SEO ayarları kaydedilemedi.");setBusy(false);}
  return <main className="admin-shell editor-shell"><header className="admin-header"><div><p>GÖRÜNÜRLÜK</p><h1>SEO yönetimi</h1></div><div><a href="/">Ana sayfayı gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card editor-card"><p className="settings-note">Bu bilgiler Google sonuçlarında ve site bağlantısı paylaşıldığında kullanılır. Marka adını seçtiğinizde buradan kolayca güncelleyebilirsiniz.</p><form className="admin-form" onSubmit={save}><label className="wide">Site başlığı<input name="seoTitle" maxLength={70} value={values.seoTitle} onChange={event=>setValues({...values,seoTitle:event.target.value})} required/><small>{values.seoTitle.length}/70 karakter</small></label><label className="wide">Site açıklaması<textarea name="seoDescription" rows={4} maxLength={170} value={values.seoDescription} onChange={event=>setValues({...values,seoDescription:event.target.value})} required/><small>{values.seoDescription.length}/170 karakter</small></label><label className="wide">Anahtar kelimeler<input name="seoKeywords" value={values.seoKeywords} onChange={event=>setValues({...values,seoKeywords:event.target.value})}/><small>Kelimeleri virgülle ayırın.</small></label><label className="wide">Paylaşım görseli<input name="seoFile" type="file" accept="image/*"/><small>Önerilen ölçü: 1200 × 630 piksel. Yeni dosya seçmezseniz mevcut görsel korunur.</small><input name="seoImageUrl" value={values.seoImageUrl} onChange={event=>setValues({...values,seoImageUrl:event.target.value})} placeholder="/og.png veya görsel bağlantısı"/></label><button disabled={busy}>{busy?"Kaydediliyor…":"SEO ayarlarını kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>;
}
