import { and, eq, isNull } from "drizzle-orm";
import { getDb } from "../../../db";
import { cartItems, carts, products, productVariants } from "../../../db/schema";

const COOKIE="store_cart";
function cookieToken(request:Request){return request.headers.get("cookie")?.split(";").map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`))?.slice(COOKIE.length+1)??null;}
async function ensureCart(request:Request){const db=getDb();let token=cookieToken(request);let [cart]=token?await db.select().from(carts).where(eq(carts.token,token)).limit(1):[];let created=false;if(!cart){token=crypto.randomUUID();[cart]=await db.insert(carts).values({token}).returning();created=true;}return{db,cart,token,created};}
function response(data:unknown,token:string,created:boolean,status=200){const headers=new Headers({"Content-Type":"application/json"});if(created)headers.set("Set-Cookie",`${COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000; Secure`);return new Response(JSON.stringify(data),{status,headers});}
export async function GET(request:Request){try{const{db,cart,token,created}=await ensureCart(request);const items=await db.select({id:cartItems.id,quantity:cartItems.quantity,productId:products.id,name:products.nameTr,nameEn:products.nameEn,slug:products.slug,imageUrl:products.imageUrl,priceTr:products.priceTr,priceGlobal:products.priceGlobal,stock:products.stock,variantId:productVariants.id,variantStock:productVariants.stock,optionName:productVariants.optionName,optionValue:productVariants.optionValue,optionNameEn:productVariants.optionNameEn,optionValueEn:productVariants.optionValueEn,priceAdjustment:productVariants.priceAdjustment}).from(cartItems).innerJoin(products,eq(cartItems.productId,products.id)).leftJoin(productVariants,eq(cartItems.variantId,productVariants.id)).where(eq(cartItems.cartId,cart.id));return response({items,market:cart.market},token,created);}catch{return Response.json({items:[],market:"TR"});}}
export async function POST(request:Request){const{db,cart,token,created}=await ensureCart(request);const body=await request.json() as {productId?:number;variantId?:number|null;quantity?:number;market?:string};const productId=Number(body.productId);const variantId=body.variantId?Number(body.variantId):null;const quantity=Math.max(1,Number(body.quantity??1));if(!productId)return response({error:"Geçersiz ürün"},token,created,400);const condition=and(eq(cartItems.cartId,cart.id),eq(cartItems.productId,productId),variantId?eq(cartItems.variantId,variantId):isNull(cartItems.variantId));const[existing]=await db.select().from(cartItems).where(condition).limit(1);if(existing)await db.update(cartItems).set({quantity:existing.quantity+quantity}).where(eq(cartItems.id,existing.id));else await db.insert(cartItems).values({cartId:cart.id,productId,variantId,quantity});if(body.market)await db.update(carts).set({market:body.market,updatedAt:new Date().toISOString()}).where(eq(carts.id,cart.id));return response({ok:true},token,created,201);}
export async function PATCH(request:Request){const{db,cart,token,created}=await ensureCart(request);const body=await request.json() as {id?:number;quantity?:number};const id=Number(body.id);const quantity=Math.max(0,Number(body.quantity??1));const[item]=await db.select().from(cartItems).where(and(eq(cartItems.id,id),eq(cartItems.cartId,cart.id))).limit(1);if(!item)return response({error:"Sepet ürünü bulunamadı"},token,created,404);if(quantity===0)await db.delete(cartItems).where(eq(cartItems.id,id));else await db.update(cartItems).set({quantity}).where(eq(cartItems.id,id));return response({ok:true},token,created);}
export async function DELETE(request:Request){const{db,cart,token,created}=await ensureCart(request);const id=Number(new URL(request.url).searchParams.get("id"));if(id)await db.delete(cartItems).where(and(eq(cartItems.id,id),eq(cartItems.cartId,cart.id)));return response({ok:true},token,created);}
