"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {requestJson} from "../../../client-request";
import "./category-editor.css";

type Category={id:number;nameTr:string;nameEn:string;slug:string;parentId:number|null;imageUrl:string;sortOrder:number;active:boolean;updatedAt:string};
type CategoryPayload={categories?:Category[];category?:Category;imageUrl?:string;error?:string};

export default function CategoryEditor({id}:{id:number}){
  const[category,setCategory]=useState<Category|null>(null);const[categories,setCategories]=useState<Category[]>([]);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const{response,data,error}=await requestJson<CategoryPayload>("/api/categories");if(!response?.ok)throw new Error(data?.error??error??"Kategori yüklenemedi.");setCategories(data?.categories??[]);setCategory((data?.categories??[]).find((item:Category)=>item.id===id)??null);setMessage("");},[id]);
  useEffect(()=>{load().catch(()=>setMessage("Kategori yüklenemedi."));},[load]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!category)return;setBusy(true);setMessage("");try{const form=new FormData(event.currentTarget);let imageUrl=String(form.get("imageUrl")??category.imageUrl);const file=form.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const uploadResult=await requestJson<CategoryPayload>("/api/uploads",{method:"POST",body:upload},30_000);if(!uploadResult.response?.ok||!uploadResult.data?.imageUrl){setMessage(uploadResult.data?.error??uploadResult.error??"Görsel yüklenemedi. Lütfen tekrar deneyin.");return;}imageUrl=uploadResult.data.imageUrl;}const{response,data,error}=await requestJson<CategoryPayload>("/api/categories",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,expectedUpdatedAt:category.updatedAt,nameTr:form.get("nameTr"),nameEn:form.get("nameEn"),slug:form.get("slug"),parentId:form.get("parentId"),imageUrl,sortOrder:form.get("sortOrder"),active:form.get("active")==="on"})});setMessage(response?.ok?"Kategori güncellendi.":data?.error??error??"Kategori güncellenemedi. Lütfen tekrar deneyin.");if(response?.ok&&data?.category)setCategory(data.category);}finally{setBusy(false);}}
  if(!category)return <main className="admin-shell"><a href="/admin">← Yönetim paneli</a><p>{message||"Kategori bulunamadı."}</p></main>;
  return <main className="admin-shell category-editor-shell"><header className="admin-header"><div><p>KATEGORİ DÜZENLEME</p><h1>{category.nameTr}</h1></div><div><a href="/magaza">Mağazayı gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><div className="category-editor-layout"><section className="admin-card"><form className="admin-form" onSubmit={save}><label>Kategori adı · Türkçe<input name="nameTr" required defaultValue={category.nameTr}/></label><label>Category name · English<input name="nameEn" defaultValue={category.nameEn}/></label><label>Kategori kodu<input name="slug" required defaultValue={category.slug}/></label><label>Sıralama<input name="sortOrder" type="number" defaultValue={category.sortOrder}/></label><label className="wide">Üst kategori<select name="parentId" defaultValue={category.parentId??""}><option value="">Ana kategori</option>{categories.filter(item=>item.id!==id&&!item.parentId).map(item=><option key={item.id} value={item.id}>{item.nameTr}</option>)}</select></label><label className="wide">Yeni kapak fotoğrafı<input name="file" type="file" accept="image/png,image/jpeg,image/webp"/><small>veya görsel bağlantısı</small><input name="imageUrl" defaultValue={category.imageUrl}/></label><div className="checks wide"><label><input name="active" type="checkbox" defaultChecked={category.active}/> Katalogda görünür</label></div><button disabled={busy}>{busy?"Kaydediliyor…":"Kategoriyi kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section><aside className="category-preview"><p>KAPAK ÖNİZLEMESİ</p><div>{category.imageUrl?<img src={category.imageUrl} alt={category.nameTr}/>:<span>Henüz görsel yok</span>}</div><h2>{category.nameTr}</h2><span>{category.nameEn||"Global ad eklenmedi"}</span></aside></div></main>;
}
