import {and,eq,exists,gt,gte,isNull,lt,lte,ne,not,or,sql} from "drizzle-orm";
import {getDb} from "../db";
import {newsletterOutbox,newsletterSubscribers,notificationOutbox,orders} from "../db/schema";
import {notificationProviderIdempotencyKey,type NotificationSource} from "./notification-delivery-key";

type Database=ReturnType<typeof getDb>;
const MAX_DELIVERY_ATTEMPTS=3;
const DELIVERY_LEASE_MS=5*60_000;

export async function claimNotificationDelivery(db:Database,input:{source:NotificationSource;id:number;now?:Date}){
  const now=input.now??new Date();const nowIso=now.toISOString();const staleBefore=new Date(now.getTime()-DELIVERY_LEASE_MS).toISOString();const claimKey=crypto.randomUUID();
  if(input.source==="order"){const orderReady=()=>exists(db.select({id:orders.id}).from(orders).where(and(eq(orders.id,notificationOutbox.orderId),eq(orders.creationState,"ready"))));await db.update(notificationOutbox).set({status:"failed",deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:null,lastError:"Gönderim sahipliği zaman aşımına uğradı ve deneme sınırı doldu.",updatedAt:nowIso}).where(and(eq(notificationOutbox.id,input.id),gte(notificationOutbox.attempts,MAX_DELIVERY_ATTEMPTS),orderReady(),or(eq(notificationOutbox.status,"draft"),and(eq(notificationOutbox.status,"sending"),or(isNull(notificationOutbox.deliveryClaimedAt),lte(notificationOutbox.deliveryClaimedAt,staleBefore))))));const[row]=await db.update(notificationOutbox).set({status:"sending",attempts:sql`${notificationOutbox.attempts}+1`,deliveryClaimKey:claimKey,deliveryClaimedAt:nowIso,nextAttemptAt:null,lastError:"",updatedAt:nowIso}).where(and(eq(notificationOutbox.id,input.id),lt(notificationOutbox.attempts,MAX_DELIVERY_ATTEMPTS),orderReady(),or(and(eq(notificationOutbox.status,"draft"),or(isNull(notificationOutbox.nextAttemptAt),lte(notificationOutbox.nextAttemptAt,nowIso))),and(eq(notificationOutbox.status,"sending"),or(isNull(notificationOutbox.deliveryClaimedAt),lte(notificationOutbox.deliveryClaimedAt,staleBefore)))))).returning();return row?{...row,providerIdempotencyKey:await notificationProviderIdempotencyKey("order",row.eventKey)}:null;}
  const newsletterEligible=()=>exists(db.select({id:newsletterSubscribers.id}).from(newsletterSubscribers).where(and(eq(newsletterSubscribers.id,newsletterOutbox.subscriberId),or(and(eq(newsletterOutbox.eventType,"verification"),eq(newsletterSubscribers.status,"pending_verification"),gt(newsletterSubscribers.verificationExpiresAt,nowIso)),and(ne(newsletterOutbox.eventType,"verification"),eq(newsletterSubscribers.status,"active"))))));const staleNewsletterLease=or(isNull(newsletterOutbox.deliveryClaimedAt),lte(newsletterOutbox.deliveryClaimedAt,staleBefore))!;
  await db.update(newsletterOutbox).set({status:"cancelled",deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:null,updatedAt:nowIso}).where(and(eq(newsletterOutbox.id,input.id),or(eq(newsletterOutbox.status,"draft"),and(eq(newsletterOutbox.status,"sending"),staleNewsletterLease)),not(newsletterEligible())));
  await db.update(newsletterOutbox).set({status:"failed",deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:null,lastError:"Gönderim sahipliği zaman aşımına uğradı ve deneme sınırı doldu.",updatedAt:nowIso}).where(and(eq(newsletterOutbox.id,input.id),gte(newsletterOutbox.attempts,MAX_DELIVERY_ATTEMPTS),newsletterEligible(),or(eq(newsletterOutbox.status,"draft"),and(eq(newsletterOutbox.status,"sending"),staleNewsletterLease))));const[row]=await db.update(newsletterOutbox).set({status:"sending",attempts:sql`${newsletterOutbox.attempts}+1`,deliveryClaimKey:claimKey,deliveryClaimedAt:nowIso,nextAttemptAt:null,lastError:"",updatedAt:nowIso}).where(and(eq(newsletterOutbox.id,input.id),lt(newsletterOutbox.attempts,MAX_DELIVERY_ATTEMPTS),newsletterEligible(),or(and(eq(newsletterOutbox.status,"draft"),or(isNull(newsletterOutbox.nextAttemptAt),lte(newsletterOutbox.nextAttemptAt,nowIso))),and(eq(newsletterOutbox.status,"sending"),staleNewsletterLease)))).returning();return row?{...row,providerIdempotencyKey:await notificationProviderIdempotencyKey("newsletter",row.eventKey)}:null;
}

export async function finishNotificationDelivery(db:Database,input:{source:NotificationSource;id:number;claimKey:string;outcome:"sent"|"failed";providerMessageId?:string;error?:string;retryAfterSeconds?:number;now?:Date}){
  const now=input.now??new Date();const nowIso=now.toISOString();const retrySeconds=Math.min(3600,Math.max(60,Math.trunc(input.retryAfterSeconds??300)));const nextAttemptAt=new Date(now.getTime()+retrySeconds*1000).toISOString();const providerMessageId=String(input.providerMessageId??"").trim().slice(0,240);const error=String(input.error??"").trim().slice(0,1000);
  if(input.source==="order"){
    const values=input.outcome==="sent"?{status:"sent",sentAt:nowIso,providerMessageId,deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:null,lastError:"",updatedAt:nowIso}:{status:sql<string>`CASE WHEN ${notificationOutbox.attempts}<${MAX_DELIVERY_ATTEMPTS} THEN 'draft' ELSE 'failed' END`,deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:sql<string|null>`CASE WHEN ${notificationOutbox.attempts}<${MAX_DELIVERY_ATTEMPTS} THEN ${nextAttemptAt} ELSE NULL END`,lastError:error||"E-posta sağlayıcısı gönderimi tamamlayamadı.",updatedAt:nowIso};
    const[row]=await db.update(notificationOutbox).set(values).where(and(eq(notificationOutbox.id,input.id),eq(notificationOutbox.status,"sending"),eq(notificationOutbox.deliveryClaimKey,input.claimKey))).returning();return row??null;
  }
  const values=input.outcome==="sent"?{status:"sent",sentAt:nowIso,providerMessageId,deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:null,lastError:"",updatedAt:nowIso}:{status:sql<string>`CASE WHEN ${newsletterOutbox.attempts}<${MAX_DELIVERY_ATTEMPTS} THEN 'draft' ELSE 'failed' END`,deliveryClaimKey:"",deliveryClaimedAt:null,nextAttemptAt:sql<string|null>`CASE WHEN ${newsletterOutbox.attempts}<${MAX_DELIVERY_ATTEMPTS} THEN ${nextAttemptAt} ELSE NULL END`,lastError:error||"E-posta sağlayıcısı gönderimi tamamlayamadı.",updatedAt:nowIso};
  const[row]=await db.update(newsletterOutbox).set(values).where(and(eq(newsletterOutbox.id,input.id),eq(newsletterOutbox.status,"sending"),eq(newsletterOutbox.deliveryClaimKey,input.claimKey))).returning();return row??null;
}
