"use client";

import { FormEvent, useState } from "react";
import "./iletisim.css";

export default function ContactPage(){
  const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[success,setSuccess]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=event.currentTarget;const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();if(response.ok){setSuccess(true);form.reset();}else setMessage(data.error??"Mesaj gönderilemedi.");setBusy(false);}
  return <main className="contact-page"><header className="contact-header"><a className="contact-brand" href="/">MYSA <span>OBJETS</span></a><nav><a href="/magaza">Mağaza</a><a href="/siparis-takip">Sipariş takibi</a></nav></header><section className="contact-hero"><p>MÜŞTERİ DESTEĞİ</p><h1>Size nasıl<br/><em>yardımcı olabiliriz?</em></h1><span>Sorularınız, ürün talepleriniz ve siparişleriniz için bize yazın. Mesajınız doğrudan mağaza yönetimine ulaşır.</span></section><section className="contact-shell">{success?<div className="contact-success"><p>MESAJINIZ ALINDI</p><h2>Teşekkür ederiz.</h2><span>Mesajınız yönetim panelimize kaydedildi. Verdiğiniz e-posta adresi üzerinden size dönüş yapılabilir.</span><a href="/">Mağazaya dön →</a></div>:<div className="contact-layout"><form onSubmit={submit} className="contact-form"><label>Ad soyad<input name="name" autoComplete="name" required/></label><label>E-posta<input name="email" type="email" autoComplete="email" required/></label><label>Sipariş numarası <small>Varsa</small><input name="orderNumber" placeholder="MS-20260713-ABC123"/></label><label>Konu<select name="subject" required defaultValue=""><option value="" disabled>Bir konu seçin</option><option>Siparişim hakkında</option><option>Ürün bilgisi</option><option>Teslimat ve iade</option><option>Toplu alım</option><option>Diğer</option></select></label><label className="wide">Mesajınız<textarea name="message" rows={7} minLength={10} required/></label><label className="contact-trap" aria-hidden="true">Şirket<input name="company" tabIndex={-1} autoComplete="off"/></label>{message&&<p className="contact-error wide" role="alert">{message}</p>}<button className="wide" disabled={busy}>{busy?"Kaydediliyor…":"Mesajı gönder"}</button></form><aside><p>HIZLI YARDIM</p><h2>Siparişinizi mi merak ediyorsunuz?</h2><span>Sipariş numaranız ve e-posta adresinizle güncel durumu anında görebilirsiniz.</span><a href="/siparis-takip">Sipariş takibine git →</a><hr/><small>Bu form ödeme bilgisi istemez. Kart veya banka bilgilerinizi mesajınıza yazmayın.</small></aside></div>}</section></main>;
}
