import {and,desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {promotions} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTUser} from "../../chatgpt-auth";
import {readBoundedJson} from "../../public-form-security";

export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401});return Response.json({promotions:await getDb().select().from(promotions).orderBy(desc(promotions.id))},{headers:{"Cache-Control":"no-store"}});}

export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});const parsed=await readBoundedJson(request,5_000);if(parsed.error)return parsed.error;const body=parsed.body!;
  const code=String(body.code??"").trim().toUpperCase();const name=String(body.name??"").trim();const market=String(body.market??"");const discountType=String(body.discountType??"");const discountValue=Number(body.discountValue);const maxDiscount=Number(body.maxDiscount??0);const minSubtotal=Number(body.minSubtotal??0);const usageLimit=Number(body.usageLimit??0);const startsAtRaw=String(body.startsAt??"").trim();const endsAtRaw=String(body.endsAt??"").trim();
  if(!/^[A-Z0-9_-]{3,40}$/.test(code)||!name||name.length>160||!["TR","GLOBAL","BOTH"].includes(market)||!["percentage","fixed"].includes(discountType))return Response.json({error:"Kampanya adı, kodu, pazarı ve indirim türü geçerli olmalıdır."},{status:400});
  if(!Number.isFinite(discountValue)||discountValue<=0||discountValue>100_000_000||(discountType==="percentage"&&discountValue>100)||!Number.isFinite(maxDiscount)||maxDiscount<0||maxDiscount>100_000_000||!Number.isFinite(minSubtotal)||minSubtotal<0||minSubtotal>100_000_000||!Number.isInteger(usageLimit)||usageLimit<0||usageLimit>1_000_000)return Response.json({error:"İndirim ve kullanım sınırı değerlerini kontrol edin."},{status:400});
  if((startsAtRaw&&Number.isNaN(new Date(startsAtRaw).getTime()))||(endsAtRaw&&Number.isNaN(new Date(endsAtRaw).getTime()))||(startsAtRaw&&endsAtRaw&&new Date(startsAtRaw)>=new Date(endsAtRaw)))return Response.json({error:"Kampanya tarih aralığı geçersiz."},{status:400});const startsAt=startsAtRaw?new Date(startsAtRaw).toISOString():null;const endsAt=endsAtRaw?new Date(endsAtRaw).toISOString():null;
  try{const[promotion]=await getDb().insert(promotions).values({code,name,market,discountType,discountValue,maxDiscount,minSubtotal,usageLimit,startsAt,endsAt,active:false}).returning();await recordAudit({user,action:"promotion.create",entityType:"promotion",entityId:promotion.id,summary:`${code} kampanyası pasif olarak oluşturuldu.`,after:{code,market,discountType,discountValue,active:false}});return Response.json({promotion},{status:201});}catch{return Response.json({error:"Bu indirim kodu daha önce kullanılmış."},{status:409});}
}

export async function PATCH(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});const parsed=await readBoundedJson(request,2_000);if(parsed.error)return parsed.error;const body=parsed.body!;const id=Number(body.id);const expectedUpdatedAt=String(body.expectedUpdatedAt??"");if(!Number.isInteger(id)||id<1||typeof body.active!=="boolean")return Response.json({error:"Geçersiz kampanya işlemi."},{status:400});if(!expectedUpdatedAt)return Response.json({error:"Kampanya ekranı güncel değil. Sayfayı yenileyip tekrar deneyin."},{status:409,headers:{"Cache-Control":"no-store"}});
  const db=getDb();const[before]=await db.select().from(promotions).where(eq(promotions.id,id)).limit(1);if(!before)return Response.json({error:"Kampanya bulunamadı."},{status:404});if(before.updatedAt!==expectedUpdatedAt)return Response.json({error:"Kampanya veya kullanım sayısı bu sırada güncellendi. Sayfayı yenileyip tekrar deneyin."},{status:409,headers:{"Cache-Control":"no-store"}});if(body.active&&before.endsAt&&new Date(before.endsAt)<=new Date())return Response.json({error:"Süresi dolmuş kampanya etkinleştirilemez."},{status:409});if(body.active&&before.usageLimit>0&&before.usedCount>=before.usageLimit)return Response.json({error:"Kullanım sınırı dolmuş kampanya etkinleştirilemez."},{status:409});
  const[promotion]=await db.update(promotions).set({active:body.active,updatedAt:new Date().toISOString()}).where(and(eq(promotions.id,id),eq(promotions.updatedAt,expectedUpdatedAt),eq(promotions.usedCount,before.usedCount))).returning();if(!promotion)return Response.json({error:"Kampanya veya kullanım sayısı bu sırada güncellendi. Sayfayı yenileyip tekrar deneyin."},{status:409,headers:{"Cache-Control":"no-store"}});await recordAudit({user,action:body.active?"promotion.activate":"promotion.deactivate",entityType:"promotion",entityId:id,summary:`${promotion.code} kampanyası ${body.active?"etkinleştirildi":"durduruldu"}.`,before:{active:before.active},after:{active:promotion.active}});return Response.json({promotion});
}
