import { getDb } from "../../../db";
import { storeSettings } from "../../../db/schema";
import { getChatGPTUser } from "../../chatgpt-auth";

export const dynamic = "force-dynamic";
const defaults = {
  brandName: "MYSA",
  brandSuffix: "OBJETS",
  brandLogoUrl: "",
  faviconUrl: "/favicon.svg",
  announcementTr: "1.500 TL üzeri ücretsiz gönderim",
  announcementGlobal: "Complimentary shipping over €150",
  showAnnouncement: "true",
  announcementUrlTr: "/magaza",
  announcementUrlGlobal: "/magaza",
  nav1Label: "Mağaza",
  nav1Url: "/magaza",
  nav2Label: "Koleksiyonlar",
  nav2Url: "/magaza",
  nav3Label: "Hikâyemiz",
  nav3Url: "#story",
  nav4Label: "Journal",
  nav4Url: "#journal",
  nav1LabelGlobal: "Shop",
  nav2LabelGlobal: "Collections",
  nav3LabelGlobal: "Our Story",
  nav4LabelGlobal: "Journal",
  heroEyebrowGlobal: "Curated pieces for considered living",
  heroTitleGlobal: "Make the everyday",
  heroTitleAccentGlobal: "extraordinary.",
  heroCopyGlobal: "Timeless objects with texture, craftsmanship and a story—for your home, wardrobe and closest companions.",
  heroButtonGlobal: "Explore the new edit",
  introTitleGlobal: "Fewer, better things.",
  introCopyGlobal: "A modern lifestyle collection spanning tactile textiles, consciously made accessories and thoughtfully selected pieces for our companions.",
  productsEyebrowGlobal: "New arrivals · Global",
  productsTitleGlobal: "Discover now",
  manifestoEyebrowGlobal: "Brand standard",
  manifestoQuoteGlobal: "Good design is not only how it looks, but how it makes your life feel.",
  manifestoPrinciple1Global: "Natural materials",
  manifestoPrinciple2Global: "Responsible production",
  manifestoPrinciple3Global: "Enduring design",
  journalEyebrowGlobal: "Living notes",
  journalTitleGlobal: "Creating small rituals at home",
  journalCopyGlobal: "Ways to turn ordinary moments into calm rituals that engage the senses.",
  journalButtonGlobal: "Read the story",
  footerTaglineGlobal: "Beautiful things for considered living.",
  newsletterTitleGlobal: "Join our letters",
  newsletterCopyGlobal: "New edits and inspiring stories, delivered occasionally.",
  footerLocationGlobal: "Istanbul · Worldwide",
  seoTitle: "MYSA OBJETS — Seçkili Yaşam Ürünleri",
  seoDescription: "Eviniz, gardırobunuz ve dostlarınız için zamansız, özenle seçilmiş yaşam ürünleri.",
  seoKeywords: "seçkili yaşam ürünleri, tekstil, ev, aksesuar, pet",
  seoImageUrl: "/og.png",
  heroEyebrow: "Yavaş yaşam için seçilmiş parçalar",
  heroTitle: "Gündelik olanı",
  heroTitleAccent: "olağanüstü kılın.",
  heroCopy: "Eviniz, gardırobunuz ve en yakın dostlarınız için; dokusu, işçiliği ve hikâyesi olan zamansız objeler.",
  heroButton: "Yeni seçkiyi keşfet",
  heroImageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=2000&q=90",
  introTitle: "Daha az, ama daha iyi.",
  introCopy: "Dokunmak isteyeceğiniz tekstillerden bilinçli üretilmiş aksesuarlara ve dostlarımız için özenle seçilmiş ürünlere uzanan modern bir yaşam koleksiyonu.",
  showCategories:"true",
  showProducts:"true",
  showJournal:"true",
  showManifesto:"true",
  homepageSectionOrder:"categories,products,custom,manifesto,journal",
  manifestoEyebrow:"Marka standardı",
  manifestoQuote:"İyi tasarım yalnızca nasıl göründüğü değil, hayatınıza nasıl hissettirdiğidir.",
  manifestoPrinciple1:"Doğal malzemeler",
  manifestoPrinciple2:"Sorumlu üretim",
  manifestoPrinciple3:"Uzun ömürlü tasarım",
  journalEyebrow:"Yaşam notları",
  journalTitle:"Evinizde küçük ritüeller yaratmak",
  journalCopy:"Sabahın ilk ışığından günün son fincanına; sıradan anları duyulara hitap eden sakin ritüellere dönüştürmenin yolları.",
  journalButton:"Yazıyı oku",
  journalImageUrl:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1300&q=90",
  footerTagline:"Beautiful things for considered living.",
  footerLocation:"İstanbul · Dünya",
  newsletterTitle:"Mektuplarımıza katılın",
  newsletterCopy:"Yeni seçkiler ve ilham veren hikâyeler.",
  instagramUrl:"",
  pinterestUrl:"",
  shippingTr:"99",
  freeShippingTr:"1500",
  shippingGlobal:"15",
  freeShippingGlobal:"150",
  shippingPolicyTr:"Sipariş talepleri onaylandıktan sonra hazırlanır. Teslimat süresi ürün ve teslimat adresine göre paylaşılır. Kargo ücreti sipariş özetinde ayrıca gösterilir.",
  returnsPolicyTr:"İade veya değişim talebiniz için sipariş numaranızla iletişim formundan bize ulaşın. Ürünün kullanılmamış ve yeniden satışa uygun durumda olması beklenir.",
  shippingPolicyGlobal:"Global order requests are reviewed before preparation. Delivery timing and available destinations are confirmed according to the products and destination country.",
  returnsPolicyGlobal:"For a return or exchange request, contact us with your order number. Products should be unused and suitable for resale.",
  privacyPolicy:"Sipariş ve iletişim formlarında paylaştığınız bilgiler; talebinizi işlemek, teslimat sürecini yürütmek ve sizinle iletişim kurmak amacıyla kaydedilir. Ödeme veya kart bilgisi bu aşamada alınmaz. Kişisel bilgilerinizi mesaj alanlarına gereğinden fazla yazmayın.",
  privacyPolicyGlobal:"Information shared through order and contact forms is stored to process your request, arrange delivery and communicate with you. Payment or card information is not collected at this stage. Do not include unnecessary personal information in message fields.",
};
export async function GET() { try { const rows = await getDb().select().from(storeSettings); return Response.json({ settings: { ...defaults, ...Object.fromEntries(rows.map(row => [row.key, row.value])) } }); } catch { return Response.json({ settings: defaults }); } }
export async function PUT(request: Request) { if (!(await getChatGPTUser())) return Response.json({ error: "Yetkisiz erişim" }, { status: 401 }); const body = await request.json() as Record<string, unknown>; const db = getDb(); const allowed = Object.keys(defaults) as (keyof typeof defaults)[]; const rows=await db.select().from(storeSettings);const current=Object.fromEntries(rows.map(row=>[row.key,row.value]));const values=Object.fromEntries(allowed.map(key=>[key,String(body[key]??current[key]??defaults[key])]));await db.batch(allowed.map(key => db.insert(storeSettings).values({ key, value: values[key], updatedAt: new Date().toISOString() }).onConflictDoUpdate({ target: storeSettings.key, set: { value: values[key], updatedAt: new Date().toISOString() } }))); return Response.json({ settings: values }); }
