"use client";

import {FormEvent,useEffect,useState} from "react";

const defaults={nav1LabelGlobal:"Shop",nav2LabelGlobal:"Collections",nav3LabelGlobal:"Our Story",nav4LabelGlobal:"Journal",heroEyebrowGlobal:"Curated pieces for considered living",heroTitleGlobal:"Make the everyday",heroTitleAccentGlobal:"extraordinary.",heroCopyGlobal:"Timeless objects with texture, craftsmanship and a story—for your home, wardrobe and closest companions.",heroButtonGlobal:"Explore the new edit",introTitleGlobal:"Fewer, better things.",introCopyGlobal:"A modern lifestyle collection spanning tactile textiles, consciously made accessories and thoughtfully selected pieces for our companions.",productsEyebrowGlobal:"New arrivals · Global",productsTitleGlobal:"Discover now",manifestoEyebrowGlobal:"Brand standard",manifestoQuoteGlobal:"Good design is not only how it looks, but how it makes your life feel.",manifestoPrinciple1Global:"Natural materials",manifestoPrinciple2Global:"Responsible production",manifestoPrinciple3Global:"Enduring design",journalEyebrowGlobal:"Living notes",journalTitleGlobal:"Creating small rituals at home",journalCopyGlobal:"Ways to turn ordinary moments into calm rituals that engage the senses.",journalButtonGlobal:"Read the story",footerTaglineGlobal:"Beautiful things for considered living.",newsletterTitleGlobal:"Join our letters",newsletterCopyGlobal:"New edits and inspiring stories, delivered occasionally.",footerLocationGlobal:"Istanbul · Worldwide"};
type Values=typeof defaults;type Key=keyof Values;
const sections:[string,[Key,string,boolean?][]][]=[
  ["Üst menü",[["nav1LabelGlobal","Menu 1"],["nav2LabelGlobal","Menu 2"],["nav3LabelGlobal","Menu 3"],["nav4LabelGlobal","Menu 4"]]],
  ["Kapak",[["heroEyebrowGlobal","Eyebrow"],["heroTitleGlobal","Main title"],["heroTitleAccentGlobal","Accent title"],["heroCopyGlobal","Description",true],["heroButtonGlobal","Button"]]],
  ["Tanıtım ve ürünler",[["introTitleGlobal","Intro title"],["introCopyGlobal","Intro description",true],["productsEyebrowGlobal","Products eyebrow"],["productsTitleGlobal","Products title"]]],
  ["Manifesto",[["manifestoEyebrowGlobal","Eyebrow"],["manifestoQuoteGlobal","Quote",true],["manifestoPrinciple1Global","Principle 1"],["manifestoPrinciple2Global","Principle 2"],["manifestoPrinciple3Global","Principle 3"]]],
  ["Journal",[["journalEyebrowGlobal","Eyebrow"],["journalTitleGlobal","Title"],["journalCopyGlobal","Description",true],["journalButtonGlobal","Button"]]],
  ["Footer ve bülten",[["footerTaglineGlobal","Brand tagline"],["newsletterTitleGlobal","Newsletter title"],["newsletterCopyGlobal","Newsletter description",true],["footerLocationGlobal","Location"]]],
];

export default function GlobalEditor(){const[values,setValues]=useState<Values>(defaults);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(data=>{setValues({...defaults,...data.settings});setMessage("");}).catch(()=>setMessage("Global içerik yüklenemedi."));},[]);const update=(key:Key,value:string)=>setValues(current=>({...current,[key]:value}));async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});setMessage(response.ok?"Global içerik güncellendi.":"Global içerik kaydedilemedi.");setBusy(false);}return <main className="admin-shell editor-shell"><header className="admin-header"><div><p>GLOBAL MAĞAZA</p><h1>İngilizce içerik yönetimi</h1></div><div><a href="/?market=GLOBAL">Ana sayfayı gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card editor-card"><p className="settings-note">Ziyaretçi GLOBAL / EUR seçtiğinde bu İngilizce metinler gösterilir. Ürün ve kategori çevirileri kendi düzenleme ekranlarından yönetilir.</p><form className="admin-form" onSubmit={save}>{sections.map(([title,fields])=><fieldset className="wide admin-form" key={title}><legend>{title}</legend>{fields.map(([key,label,long])=><label className={long?"wide":undefined} key={key}>{label}{long?<textarea rows={3} value={values[key]} onChange={event=>update(key,event.target.value)}/>:<input value={values[key]} onChange={event=>update(key,event.target.value)}/>}</label>)}</fieldset>)}<button disabled={busy}>{busy?"Kaydediliyor…":"Global içeriği kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>}
