import {and,desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {orders,privacyRequests} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTUser} from "../../chatgpt-auth";
import {enforceRateLimit} from "../../rate-limit";
import {containsLikelyCardNumber,isValidEmail,isValidOrderNumber,isValidRequestKey,normalizeEmail,readBoundedJson} from "../../public-form-security";

export const dynamic="force-dynamic";const noStore={"Cache-Control":"no-store"};

export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const requests=await getDb().select().from(privacyRequests).orderBy(desc(privacyRequests.id)).limit(500);return Response.json({requests},{headers:noStore});}

export async function POST(request:Request){const parsed=await readBoundedJson(request,12_000);if(parsed.error)return parsed.error;const body=parsed.body!;if(String(body.company??"").trim())return Response.json({ok:true},{status:201,headers:noStore});const name=String(body.name??"").trim().slice(0,120);const email=normalizeEmail(body.email);const phone=String(body.phone??"").trim().slice(0,40);const requestType=String(body.requestType??"");const details=String(body.details??"").trim().slice(0,4000);const orderNumber=String(body.orderNumber??"").trim().toUpperCase().slice(0,40);const requestKey=String(body.requestKey??"");if(name.length<2||!isValidEmail(email)||!isValidRequestKey(requestKey)||(orderNumber&&!isValidOrderNumber(orderNumber))||!["access","correction","deletion","processing_objection","other"].includes(requestType)||details.length<10||body.privacyAcknowledged!==true)return Response.json({error:"Zorunlu bilgileri ve gizlilik onayını eksiksiz doldurun."},{status:400,headers:noStore});if(containsLikelyCardNumber(details))return Response.json({error:"Güvenliğiniz için talebinize kart numarası yazmayın."},{status:400,headers:noStore});const limited=await enforceRateLimit(request,{scope:"privacy_request",identifier:email,limit:3,windowMinutes:60});if(limited)return limited;const db=getDb();const[duplicate]=await db.select().from(privacyRequests).where(eq(privacyRequests.requestKey,requestKey)).limit(1);if(duplicate)return Response.json({ok:true,requestNumber:duplicate.requestNumber,dueAt:duplicate.dueAt},{status:200,headers:noStore});const[matchedOrder]=orderNumber?await db.select({id:orders.id}).from(orders).where(and(eq(orders.orderNumber,orderNumber),eq(orders.email,email))).limit(1):[];const now=new Date();const dueAt=new Date(now.getTime()+30*24*60*60*1000).toISOString();const requestNumber=`VR-${now.toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const[row]=await db.insert(privacyRequests).values({requestKey,requestNumber,name,email,phone,requestType,details,privacyAcknowledgedAt:now.toISOString(),orderNumber,orderId:matchedOrder?.id??null,dueAt}).onConflictDoNothing({target:privacyRequests.requestKey}).returning();if(!row){const[retry]=await db.select().from(privacyRequests).where(eq(privacyRequests.requestKey,requestKey)).limit(1);if(retry)return Response.json({ok:true,requestNumber:retry.requestNumber,dueAt:retry.dueAt},{status:200,headers:noStore});return Response.json({error:"Talep kaydedilemedi."},{status:409,headers:noStore});}return Response.json({ok:true,requestNumber,dueAt},{status:201,headers:noStore});}

export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const id=Number(body?.id);const status=String(body?.status??"");const identityStatus=String(body?.identityStatus??"");if(!id||!["new","reviewing","waiting_identity","completed","rejected"].includes(status)||!["unverified","pending","verified","rejected"].includes(identityStatus))return Response.json({error:"Geçersiz veri talebi güncellemesi."},{status:400,headers:noStore});const db=getDb();const[before]=await db.select().from(privacyRequests).where(eq(privacyRequests.id,id)).limit(1);if(!before)return Response.json({error:"Talep bulunamadı."},{status:404,headers:noStore});const now=new Date().toISOString();const assignedTo=String(body?.assignedTo??before.assignedTo).trim().slice(0,180);const adminNote=String(body?.adminNote??before.adminNote).trim().slice(0,2000);const responseSummary=String(body?.responseSummary??before.responseSummary).trim().slice(0,2000);if(["completed","rejected"].includes(status)&&!responseSummary)return Response.json({error:"Talep sonuçlandırılırken cevap özeti zorunludur."},{status:409,headers:noStore});const[updated]=await db.update(privacyRequests).set({status,identityStatus,assignedTo,adminNote,responseSummary,resolvedAt:["completed","rejected"].includes(status)?before.resolvedAt??now:null,updatedAt:now}).where(eq(privacyRequests.id,id)).returning();await recordAudit({user,action:"privacy_request.update",entityType:"privacy_request",entityId:id,summary:`${before.requestNumber} veri talebi güncellendi.`,before:{status:before.status,identityStatus:before.identityStatus,assignedTo:before.assignedTo},after:{status,identityStatus,assignedTo,resolvedAt:updated.resolvedAt}});return Response.json({request:updated},{headers:noStore});}
