"use client";

import {FormEvent,useEffect,useState} from "react";
import {requestJson} from "../../../client-request";
import "./variant-editor.css";

type Product={id:number;nameTr:string};type Variant={id:number;productId:number;sku:string;optionName:string;optionValue:string;optionNameEn:string;optionValueEn:string;stock:number;priceAdjustment:number;active:boolean;updatedAt:string};
type VariantPayload={variants?:Variant[];variant?:Variant;error?:string};type ProductPayload={products?:Product[];error?:string};

export default function VariantEditor({id}:{id:number}){
  const[variant,setVariant]=useState<Variant|null>(null);const[products,setProducts]=useState<Product[]>([]);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  useEffect(()=>{void Promise.all([requestJson<VariantPayload>("/api/variants"),requestJson<ProductPayload>("/api/products")]).then(([v,p])=>{if(!v.response?.ok||!p.response?.ok)throw new Error(v.data?.error??p.data?.error??v.error??p.error??"Seçenek yüklenemedi.");setVariant((v.data?.variants??[]).find((item:Variant)=>item.id===id)??null);setProducts(p.data?.products??[]);setMessage("");}).catch(error=>setMessage(error instanceof Error?error.message:"Seçenek yüklenemedi."));},[id]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!variant)return;const form=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);setMessage("");try{const{response,data,error}=await requestJson<VariantPayload>("/api/variants",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,expectedUpdatedAt:variant.updatedAt,...form,active:form.active==="on"})});setMessage(response?.ok?"Ürün seçeneği güncellendi.":data?.error??error??"Seçenek güncellenemedi. Lütfen tekrar deneyin.");if(response?.ok&&data?.variant)setVariant(data.variant);}finally{setBusy(false);}}
  if(!variant)return <main className="admin-shell"><a href="/admin">← Yönetim paneli</a><p>{message||"Seçenek bulunamadı."}</p></main>;
  return <main className="admin-shell variant-editor-shell"><header className="admin-header"><div><p>ÜRÜN SEÇENEĞİ</p><h1>{variant.optionName}: {variant.optionValue}</h1></div><div><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card variant-editor-card"><form onSubmit={save} className="admin-form"><label className="wide">Ürün<select name="productId" defaultValue={variant.productId}>{products.map(product=><option key={product.id} value={product.id}>{product.nameTr}</option>)}</select></label><label>Seçenek türü · Türkçe<input name="optionName" required defaultValue={variant.optionName}/></label><label>Seçenek değeri · Türkçe<input name="optionValue" required defaultValue={variant.optionValue}/></label><label>Option type · English<input name="optionNameEn" defaultValue={variant.optionNameEn}/></label><label>Option value · English<input name="optionValueEn" defaultValue={variant.optionValueEn}/></label><label>Ürün kodu · SKU<input name="sku" required defaultValue={variant.sku}/></label><label>Stok<input name="stock" type="number" min="0" defaultValue={variant.stock}/></label><label>Fiyat farkı<input name="priceAdjustment" type="number" step="0.01" defaultValue={variant.priceAdjustment}/></label><label className="wide"><input name="active" type="checkbox" defaultChecked={variant.active}/> Satışta kullanılabilir</label><button disabled={busy}>{busy?"Kaydediliyor…":"Seçeneği kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>;
}
