import {and,desc,eq,sql} from "drizzle-orm";
import {getDb} from "../../../db";
import {inventoryMovements,products,productVariants,replenishments} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTUser} from "../../chatgpt-auth";

export const dynamic="force-dynamic";
const reference=()=>`TD-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;

export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401});const db=getDb();const[rows,productRows,variantRows]=await Promise.all([db.select().from(replenishments).orderBy(desc(replenishments.id)).limit(500),db.select().from(products).orderBy(desc(products.id)),db.select().from(productVariants)]);return Response.json({replenishments:rows,products:productRows,variants:variantRows},{headers:{"Cache-Control":"no-store"}});}

export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const productId=Number(body?.productId);const variantId=Number(body?.variantId)||null;const quantity=Number(body?.quantity);const expectedRaw=String(body?.expectedAt??"").trim();const expectedDate=expectedRaw?new Date(expectedRaw):null;if(!productId||!Number.isInteger(quantity)||quantity<1||quantity>100000||(expectedDate&&Number.isNaN(expectedDate.getTime())))return Response.json({error:"Ürün, adet veya beklenen tarih geçersiz."},{status:400});const expectedAt=expectedDate?.toISOString()??null;const db=getDb();const[product]=await db.select().from(products).where(eq(products.id,productId)).limit(1);if(!product)return Response.json({error:"Ürün bulunamadı."},{status:404});let variantLabel="";if(variantId){const[variant]=await db.select().from(productVariants).where(and(eq(productVariants.id,variantId),eq(productVariants.productId,productId))).limit(1);if(!variant)return Response.json({error:"Varyant bu ürüne ait değil."},{status:400});variantLabel=`${variant.optionName}: ${variant.optionValue}`;}
  const supplierName=String(body?.supplierName??product.supplierName).trim().slice(0,160);const note=String(body?.note??"").trim().slice(0,1000);const[row]=await db.insert(replenishments).values({reference:reference(),productId,variantId,productName:product.nameTr,variantLabel,sourcingType:product.sourcingType,supplierName,quantity,unitCost:product.unitCost,status:"draft",expectedAt,note,actorEmail:user.email}).returning();await recordAudit({user,action:"replenishment.create",entityType:"replenishment",entityId:row.id,summary:`${row.reference} tedarik taslağı oluşturuldu.`,after:{productName:row.productName,variantLabel,quantity,supplierName,status:"draft"}});return Response.json({replenishment:row},{status:201});
}

export async function PATCH(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});const body=await request.json().catch(()=>null) as {id?:number;action?:string}|null;const id=Number(body?.id);const action=String(body?.action??"");if(!id||!["ordered","received","cancelled"].includes(action))return Response.json({error:"Geçersiz tedarik işlemi."},{status:400});const db=getDb();const[before]=await db.select().from(replenishments).where(eq(replenishments.id,id)).limit(1);if(!before)return Response.json({error:"Tedarik kaydı bulunamadı."},{status:404});const now=new Date().toISOString();
  if(action==="ordered"){if(before.status!=="draft")return Response.json({error:"Yalnızca taslak kayıt sipariş verildi olarak işaretlenebilir."},{status:409});if(!before.supplierName)return Response.json({error:"Sipariş verildi kaydı için tedarikçi adı zorunludur."},{status:409});const[row]=await db.update(replenishments).set({status:"ordered",orderedAt:now,actorEmail:user.email,updatedAt:now}).where(and(eq(replenishments.id,id),eq(replenishments.status,"draft"))).returning();if(!row)return Response.json({error:"Tedarik kaydı başka bir işlemde değiştirildi."},{status:409});await recordAudit({user,action:"replenishment.ordered",entityType:"replenishment",entityId:id,summary:`${row.reference} sipariş verildi olarak kaydedildi.`,before:{status:before.status},after:{status:row.status,orderedAt:row.orderedAt}});return Response.json({replenishment:row});}
  if(action==="cancelled"){if(!["draft","ordered"].includes(before.status))return Response.json({error:"Teslim alınan kayıt iptal edilemez."},{status:409});const[row]=await db.update(replenishments).set({status:"cancelled",actorEmail:user.email,updatedAt:now}).where(and(eq(replenishments.id,id),eq(replenishments.status,before.status))).returning();if(!row)return Response.json({error:"Tedarik kaydı başka bir işlemde değiştirildi."},{status:409});await recordAudit({user,action:"replenishment.cancel",entityType:"replenishment",entityId:id,summary:`${row.reference} iptal edildi.`,before:{status:before.status},after:{status:row.status}});return Response.json({replenishment:row});}
  if(before.status!=="ordered")return Response.json({error:"Yalnızca sipariş verilmiş kayıt teslim alınabilir."},{status:409});if(!before.productId)return Response.json({error:"Ürün katalogdan kaldırıldığı için otomatik stok girişi yapılamaz."},{status:409});let currentStock:number|undefined;if(before.variantId){const[current]=await db.select({stock:productVariants.stock}).from(productVariants).where(and(eq(productVariants.id,before.variantId),eq(productVariants.productId,before.productId))).limit(1);currentStock=current?.stock;}else{const[current]=await db.select({stock:products.stock}).from(products).where(eq(products.id,before.productId)).limit(1);currentStock=current?.stock;}if(currentStock===undefined)return Response.json({error:"Stok kalemi artık bulunamadığı için teslim alınamadı."},{status:409});const[claimed]=await db.update(replenishments).set({status:"received",receivedAt:now,actorEmail:user.email,updatedAt:now}).where(and(eq(replenishments.id,id),eq(replenishments.status,"ordered"))).returning();if(!claimed)return Response.json({error:"Bu tedarik kaydı daha önce işlendi."},{status:409});let stockApplied=false;let nextStock:number|undefined;try{if(before.variantId){const[updated]=await db.update(productVariants).set({stock:sql`${productVariants.stock}+${before.quantity}`}).where(eq(productVariants.id,before.variantId)).returning({stock:productVariants.stock});nextStock=updated?.stock;}else{const[updated]=await db.update(products).set({stock:sql`${products.stock}+${before.quantity}`,updatedAt:now}).where(eq(products.id,before.productId)).returning({stock:products.stock});nextStock=updated?.stock;}if(nextStock===undefined)throw new Error("stock target missing");stockApplied=true;await db.insert(inventoryMovements).values({productId:before.productId,variantId:before.variantId,movementType:before.sourcingType==="handmade"?"production":"purchase",quantityDelta:before.quantity,previousStock:nextStock-before.quantity,nextStock,reason:"Tedarik kaydı teslim alındı",reference:before.reference,actorEmail:user.email});}catch{if(stockApplied){if(before.variantId)await db.update(productVariants).set({stock:sql`${productVariants.stock}-${before.quantity}`}).where(eq(productVariants.id,before.variantId));else await db.update(products).set({stock:sql`${products.stock}-${before.quantity}`,updatedAt:now}).where(eq(products.id,before.productId));}await db.update(replenishments).set({status:"ordered",receivedAt:null,updatedAt:now}).where(eq(replenishments.id,id));return Response.json({error:"Stok girişi tamamlanamadı; tedarik kaydı beklemeye geri alındı."},{status:500});}await recordAudit({user,action:"replenishment.receive",entityType:"replenishment",entityId:id,summary:`${before.reference} teslim alındı ve stok +${before.quantity} güncellendi.`,before:{status:before.status,stock:nextStock-before.quantity},after:{status:"received",stock:nextStock}});return Response.json({replenishment:claimed,nextStock});
}
