"use client";

import{FormEvent,useCallback,useEffect,useState}from"react";
import{requestJson}from"../../client-request";

type Media={key:string;url:string;size:number;uploaded:string;usedBy:string[]};
type BackupPart={number:number;count:number;size:number};
type BackupManifest={snapshot:string;count:number;totalBytes:number;parts:BackupPart[];individual:{key:string;size:number}[]};
type MediaPayload={items?:Media[];error?:string};
type BackupPayload=BackupManifest&{error?:string};

const bytes=(value:number)=>value>=1024*1024?`${(value/(1024*1024)).toFixed(1)} MB`:`${Math.ceil(value/1024)} KB`;

export default function MediaLibrary({isOwner}:{isOwner:boolean}){
  const[items,setItems]=useState<Media[]>([]);const[backup,setBackup]=useState<BackupManifest|null>(null);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const[mediaResult,backupResult]=await Promise.all([requestJson<MediaPayload>("/api/media-library"),isOwner?requestJson<BackupPayload>("/api/media-backup"):Promise.resolve(null)]);if(!mediaResult.response?.ok){setMessage(mediaResult.data?.error??mediaResult.error??"Medya kütüphanesi yüklenemedi. Lütfen tekrar deneyin.");return;}setItems(mediaResult.data?.items??[]);if(backupResult){if(!backupResult.response?.ok||!backupResult.data){setMessage(backupResult.data?.error??backupResult.error??"Medya yedek listesi hazırlanamadı. Lütfen tekrar deneyin.");return;}setBackup(backupResult.data);}setMessage("");},[isOwner]);
  useEffect(()=>{void load();},[load]);
  async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=form.elements.namedItem("file")as HTMLInputElement;if(!input.files?.[0])return;setBusy(true);try{const body=new FormData();body.set("file",input.files[0]);const{response,data,error}=await requestJson<MediaPayload>("/api/uploads",{method:"POST",body},30_000);setMessage(response?.ok?"Görsel yüklendi.":data?.error??error??"Görsel yüklenemedi. Lütfen tekrar deneyin.");if(response?.ok){form.reset();await load();}}finally{setBusy(false);}}
  async function remove(item:Media){if(!window.confirm("Bu kullanılmayan görsel kalıcı olarak silinsin mi?"))return;setBusy(true);try{const{response,data,error}=await requestJson<MediaPayload>("/api/media-library",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:item.key})});setMessage(response?.ok?"Görsel silindi.":data?.error??error??"Görsel silinemedi. Lütfen tekrar deneyin.");if(response?.ok)await load();}finally{setBusy(false);}}
  async function copy(url:string){try{await navigator.clipboard.writeText(url);setMessage("Görsel bağlantısı kopyalandı.");}catch{setMessage("Bağlantı kopyalanamadı. Tarayıcı pano iznini kontrol edin.");}}
  async function downloadPart(part:BackupPart){if(!backup)return;setBusy(true);setMessage("");try{const response=await fetch(`/api/media-backup?part=${part.number}&snapshot=${backup.snapshot}`);if(!response.ok){const data=await response.json().catch(()=>null);setMessage(data?.error??"Medya yedek parçası hazırlanamadı.");if(response.status===409)await load();return;}const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);try{const anchor=document.createElement("a");anchor.href=objectUrl;anchor.download=`mysa-medya-yedegi-${new Date().toISOString().slice(0,10)}-parca-${part.number}-${backup.parts.length}.zip`;document.body.append(anchor);anchor.click();anchor.remove();}finally{URL.revokeObjectURL(objectUrl);}setMessage(`${part.number}. medya yedek parçası indirildi.`);}catch{setMessage("Medya yedeği indirilemedi. Bağlantınızı kontrol edip tekrar deneyin.");}finally{setBusy(false);}}
  return <main className="admin-shell editor-shell media-library"><header className="admin-header"><div><p>MEDYA</p><h1>Görsel kütüphanesi</h1></div><div><a href="/">Mağazayı gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card media-upload"><div><h2>Yeni görsel yükle</h2><p className="settings-note">En fazla 8 MB; PNG, JPG veya WebP.</p></div><form onSubmit={upload}><input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/><button disabled={busy}>{busy?"İşleniyor…":"Yükle"}</button></form></section>{isOwner&&<section className="admin-card media-backup-card"><div><p className="section-kicker">DOSYA YEDEĞİ</p><h2>Ürün görsellerinin kopyası</h2><p>Görseller boyut sınırına göre ZIP parçalarına ayrılır. Her parça dosya adlarını, boyutlarını ve SHA-256 özetlerini içeren bir envanterle birlikte hazırlanır.</p></div>{backup?<div className="media-backup-actions"><span><b>{backup.count}</b> dosya · {bytes(backup.totalBytes)} · {backup.parts.length} ZIP parçası</span>{backup.parts.map(part=><button key={part.number} onClick={()=>downloadPart(part)} disabled={busy}>{part.number}. parçayı indir · {part.count} dosya · {bytes(part.size)}</button>)}{backup.individual.length>0&&<small>{backup.individual.length} büyük dosya aşağıdaki tekil indirme düğmeleriyle alınmalıdır.</small>}{backup.count===0&&<small>Yedeklenecek yüklenmiş görsel bulunmuyor.</small>}</div>:<p>Medya envanteri hazırlanıyor…</p>}</section>}{message&&<p className="admin-message" role="status">{message}</p>}<section className="media-grid">{items.map(item=><article className="admin-card" key={item.key}><img src={item.url} alt=""/><div><b>{item.key.split("/").pop()}</b><small>{bytes(item.size)} · {new Date(item.uploaded).toLocaleDateString("tr-TR")}</small>{item.usedBy.length?<small>Kullanım: {item.usedBy.join(", ")}</small>:<small>Kullanılmıyor · güvenle silinebilir</small>}<nav><button onClick={()=>copy(item.url)}>Bağlantıyı kopyala</button>{isOwner&&<a href={`/api/media-backup?key=${encodeURIComponent(item.key)}`}>Dosyayı indir</a>}<button onClick={()=>remove(item)} disabled={item.usedBy.length>0||busy}>{item.usedBy.length?"Kullanımda":"Sil"}</button></nav></div></article>)}</section>{!items.length&&!message&&<p className="admin-card empty">Henüz yüklenmiş görsel yok.</p>}</main>;
}
