import { getDb } from "../../../../db";
import { categories, products } from "../../../../db/schema";
import { getChatGPTUser } from "../../../chatgpt-auth";

function parseCsv(input:string){const text=input.replace(/^\uFEFF/,"");const firstLine=text.split(/\r?\n/,1)[0]??"";const delimiter=(firstLine.match(/;/g)?.length??0)>(firstLine.match(/,/g)?.length??0)?";":",";const rows:string[][]=[];let row:string[]=[];let cell="";let quoted=false;for(let index=0;index<text.length;index++){const char=text[index];if(char==='"'){if(quoted&&text[index+1]==='"'){cell+='"';index++;}else quoted=!quoted;}else if(char===delimiter&&!quoted){row.push(cell.trim());cell="";}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[index+1]==='\n')index++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell="";}else cell+=char;}row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)return[];const headers=rows[0].map(value=>value.trim());return rows.slice(1).map(values=>Object.fromEntries(headers.map((header,index)=>[header,values[index]??""])));}
const bool=(value:string,fallback:boolean)=>value.trim()===""?fallback:["1","true","evet","yes","aktif"].includes(value.trim().toLocaleLowerCase("tr-TR"));
const number=(value:string)=>{const normalized=value.trim().replaceAll(" ","").replace(",",".");const parsed=Number(normalized);return Number.isFinite(parsed)?Math.max(0,parsed):0;};
const csvCell=(value:unknown)=>`"${String(value).replaceAll('"','""')}"`;

export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401});const sample={nameTr:"Organik Havlu",nameEn:"Organic Towel",slug:"organik-havlu",descriptionTr:"Ürün açıklaması",descriptionEn:"Product description",categorySlug:"banyo-ev",imageUrl:"https://...",priceTr:499,priceGlobal:24,stock:20,marketTr:"Evet",marketGlobal:"Evet",active:"Evet"};const headers=Object.keys(sample);const csv=`\uFEFF${headers.map(csvCell).join(",")}\r\n${Object.values(sample).map(csvCell).join(",")}`;return new Response(csv,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":"attachment; filename=urun-yukleme-sablonu.csv","Cache-Control":"no-store"}});}

export async function POST(request:Request){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401});const form=await request.formData();const file=form.get("file");if(!(file instanceof File)||!file.size)return Response.json({error:"CSV dosyası seçin."},{status:400});if(file.size>2_000_000)return Response.json({error:"Dosya 2 MB sınırını aşıyor."},{status:413});const rows=parseCsv(await file.text());if(!rows.length)return Response.json({error:"CSV içinde ürün satırı bulunamadı."},{status:400});if(rows.length>250)return Response.json({error:"Tek seferde en fazla 250 ürün aktarabilirsiniz."},{status:400});const db=getDb();const[categoryRows,productRows]=await Promise.all([db.select().from(categories),db.select({slug:products.slug}).from(products)]);const categoryMap=new Map(categoryRows.map(category=>[category.slug,category.id]));const existing=new Set(productRows.map(product=>product.slug));let created=0;let updated=0;const errors:string[]=[];for(let index=0;index<rows.length;index++){const source=rows[index];const nameTr=String(source.nameTr??"").trim();const slug=String(source.slug??"").trim().toLocaleLowerCase("en-US");const categorySlug=String(source.categorySlug??"").trim();if(!nameTr){errors.push(`${index+2}. satır: Türkçe ürün adı eksik.`);continue;}if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)){errors.push(`${index+2}. satır: Ürün kodu yalnızca küçük harf, rakam ve tire içermeli.`);continue;}if(categorySlug&&!categoryMap.has(categorySlug)){errors.push(`${index+2}. satır: ${categorySlug} kategori kodu bulunamadı.`);continue;}const values={nameTr,nameEn:String(source.nameEn??"").trim(),slug,descriptionTr:String(source.descriptionTr??"").trim(),descriptionEn:String(source.descriptionEn??"").trim(),categoryId:categorySlug?categoryMap.get(categorySlug)!:null,imageUrl:String(source.imageUrl??"").trim(),priceTr:number(String(source.priceTr??"")),priceGlobal:number(String(source.priceGlobal??"")),stock:Math.floor(number(String(source.stock??""))),marketTr:bool(String(source.marketTr??""),true),marketGlobal:bool(String(source.marketGlobal??""),false),active:bool(String(source.active??""),true),updatedAt:new Date().toISOString()};try{await db.insert(products).values(values).onConflictDoUpdate({target:products.slug,set:values});if(existing.has(slug))updated++;else{created++;existing.add(slug);}}catch{errors.push(`${index+2}. satır: Ürün kaydedilemedi.`);}}return Response.json({created,updated,skipped:errors.length,errors:errors.slice(0,30)});}
