import {desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {newsletterOutbox,notificationOutbox,orders} from "../../../db/schema";
import {getChatGPTUser} from "../../chatgpt-auth";
import {getIntegrationStatus} from "../../integrations/runtime";

export const dynamic="force-dynamic";const noStore={"Cache-Control":"no-store"};
export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const db=getDb();const[orderRows,newsletterRows]=await Promise.all([db.select({id:notificationOutbox.id,orderId:notificationOutbox.orderId,eventType:notificationOutbox.eventType,recipient:notificationOutbox.recipient,subject:notificationOutbox.subject,body:notificationOutbox.body,status:notificationOutbox.status,attempts:notificationOutbox.attempts,lastError:notificationOutbox.lastError,sentAt:notificationOutbox.sentAt,createdAt:notificationOutbox.createdAt,orderNumber:orders.orderNumber}).from(notificationOutbox).innerJoin(orders,eq(notificationOutbox.orderId,orders.id)).orderBy(desc(notificationOutbox.id)).limit(300),db.select().from(newsletterOutbox).orderBy(desc(newsletterOutbox.id)).limit(300)]);const notifications=[...orderRows.map(row=>({...row,source:"order"})),...newsletterRows.map(row=>({...row,source:"newsletter",orderId:null,orderNumber:"Bülten"}))].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,500);const integration=getIntegrationStatus();return Response.json({notifications,providerConnected:false,providerConfigured:integration.email.credentialsConfigured,emailMode:integration.email.mode},{headers:noStore});}
export async function PATCH(request:Request){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const id=Number(body?.id);const status=String(body?.status);const source=body?.source==="newsletter"?"newsletter":"order";if(!id||!["draft","dismissed"].includes(status))return Response.json({error:"Geçersiz bildirim işlemi"},{status:400,headers:noStore});const db=getDb();const[row]=source==="newsletter"?await db.update(newsletterOutbox).set({status,updatedAt:new Date().toISOString()}).where(eq(newsletterOutbox.id,id)).returning():await db.update(notificationOutbox).set({status,updatedAt:new Date().toISOString()}).where(eq(notificationOutbox.id,id)).returning();return row?Response.json({notification:row},{headers:noStore}):Response.json({error:"Bildirim bulunamadı"},{status:404,headers:noStore});}
