"use client";

import {FormEvent,useEffect,useState} from "react";
type Product={id:number;nameTr:string;slug:string;descriptionTr:string;categoryId:number|null;imageUrl:string;priceTr:number;priceGlobal:number;stock:number;marketTr:boolean;marketGlobal:boolean;active:boolean};
type Category={id:number;nameTr:string;parentId:number|null};
export default function ProductEditor({id}:{id:number}){const [product,setProduct]=useState<Product|null>(null);const [categories,setCategories]=useState<Category[]>([]);const [message,setMessage]=useState("Yükleniyor…");const [busy,setBusy]=useState(false);
useEffect(()=>{Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/categories").then(r=>r.json())]).then(([p,c])=>{setProduct((p.products??[]).find((item:Product)=>item.id===id)??null);setCategories(c.categories??[]);setMessage("");}).catch(()=>setMessage("Ürün yüklenemedi."));},[id]);
async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!product)return;setBusy(true);const form=new FormData(event.currentTarget);let imageUrl=String(form.get("imageUrl")??product.imageUrl);const file=form.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body:upload});const data=await response.json();if(!response.ok){setMessage(data.error);setBusy(false);return;}imageUrl=data.imageUrl;}const body={id,nameTr:form.get("nameTr"),slug:form.get("slug"),descriptionTr:form.get("descriptionTr"),categoryId:form.get("categoryId"),imageUrl,priceTr:form.get("priceTr"),priceGlobal:form.get("priceGlobal"),stock:form.get("stock"),marketTr:form.get("marketTr")==="on",marketGlobal:form.get("marketGlobal")==="on",active:form.get("active")==="on"};const response=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?"Değişiklikler kaydedildi.":data.error??"Kaydedilemedi.");if(response.ok)setProduct(data.product);setBusy(false);}
if(!product)return <main className="admin-shell"><a href="/admin">← Yönetim paneli</a><p>{message||"Ürün bulunamadı."}</p></main>;
return <main className="admin-shell editor-shell"><header className="admin-header"><div><p>ÜRÜN DÜZENLEME</p><h1>{product.nameTr}</h1></div><div><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card editor-card"><form onSubmit={save} className="admin-form"><label>Ürün adı<input name="nameTr" required defaultValue={product.nameTr}/></label><label>Ürün kodu / adresi<input name="slug" required defaultValue={product.slug}/></label><label className="wide">Kategori<select name="categoryId" defaultValue={product.categoryId??""}><option value="">Kategorisiz</option>{categories.map(c=><option key={c.id} value={c.id}>{c.parentId?"— ":""}{c.nameTr}</option>)}</select></label><label className="wide">Açıklama<textarea name="descriptionTr" rows={5} defaultValue={product.descriptionTr}/></label><label>Türkiye fiyatı<input name="priceTr" type="number" step="0.01" min="0" defaultValue={product.priceTr}/></label><label>Global fiyat (€)<input name="priceGlobal" type="number" step="0.01" min="0" defaultValue={product.priceGlobal}/></label><label>Stok<input name="stock" type="number" min="0" defaultValue={product.stock}/></label><label className="wide">Yeni görsel<input name="file" type="file" accept="image/*"/><small>Mevcut bağlantı</small><input name="imageUrl" defaultValue={product.imageUrl}/></label><div className="checks wide"><label><input name="marketTr" type="checkbox" defaultChecked={product.marketTr}/> Türkiye</label><label><input name="marketGlobal" type="checkbox" defaultChecked={product.marketGlobal}/> Global</label><label><input name="active" type="checkbox" defaultChecked={product.active}/> Yayında</label></div><button disabled={busy}>{busy?"Kaydediliyor…":"Değişiklikleri kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section></main>}
