"use client";

import { FormEvent, useEffect, useState } from "react";
import "./gallery-editor.css";

type Product={id:number;nameTr:string;slug:string;descriptionTr:string;categoryId:number|null;imageUrl:string;priceTr:number;priceGlobal:number;stock:number;marketTr:boolean;marketGlobal:boolean;active:boolean};
type Category={id:number;nameTr:string;parentId:number|null};
type ProductImage={id:number;productId:number;imageUrl:string;altText:string;sortOrder:number};

export default function ProductEditor({id}:{id:number}){
  const[product,setProduct]=useState<Product|null>(null);const[categories,setCategories]=useState<Category[]>([]);const[images,setImages]=useState<ProductImage[]>([]);const[message,setMessage]=useState("Yükleniyor…");const[busy,setBusy]=useState(false);
  const load=async()=>{const[p,c,g]=await Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/categories").then(r=>r.json()),fetch(`/api/product-images?productId=${id}`).then(r=>r.json())]);setProduct((p.products??[]).find((item:Product)=>item.id===id)??null);setCategories(c.categories??[]);setImages(g.images??[]);setMessage("");};
  useEffect(()=>{load().catch(()=>setMessage("Ürün yüklenemedi."));},[id]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!product)return;setBusy(true);const form=new FormData(event.currentTarget);let imageUrl=String(form.get("imageUrl")??product.imageUrl);const file=form.get("file");if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body:upload});const data=await response.json();if(!response.ok){setMessage(data.error);setBusy(false);return;}imageUrl=data.imageUrl;}const body={id,nameTr:form.get("nameTr"),slug:form.get("slug"),descriptionTr:form.get("descriptionTr"),categoryId:form.get("categoryId"),imageUrl,priceTr:form.get("priceTr"),priceGlobal:form.get("priceGlobal"),stock:form.get("stock"),marketTr:form.get("marketTr")==="on",marketGlobal:form.get("marketGlobal")==="on",active:form.get("active")==="on"};const response=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await response.json();setMessage(response.ok?"Değişiklikler kaydedildi.":data.error??"Kaydedilemedi.");if(response.ok)setProduct(data.product);setBusy(false);}
  async function uploadGallery(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!product)return;const input=event.currentTarget.elements.namedItem("galleryFiles") as HTMLInputElement;const files=Array.from(input.files??[]);if(!files.length){setMessage("Galeri için en az bir görsel seçin.");return;}setBusy(true);for(const[index,file]of files.entries()){const upload=new FormData();upload.set("file",file);const uploadResponse=await fetch("/api/uploads",{method:"POST",body:upload});const uploadData=await uploadResponse.json();if(!uploadResponse.ok){setMessage(uploadData.error);setBusy(false);return;}await fetch("/api/product-images",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:id,imageUrl:uploadData.imageUrl,altText:product.nameTr,sortOrder:images.length+index})});if(!product.imageUrl&&index===0)await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,imageUrl:uploadData.imageUrl})});}event.currentTarget.reset();await load();setBusy(false);setMessage(`${files.length} görsel galeriye eklendi.`);}
  async function makeCover(image:ProductImage){const response=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,imageUrl:image.imageUrl})});if(response.ok){setProduct(current=>current?{...current,imageUrl:image.imageUrl}:current);setMessage("Kapak görseli güncellendi.");}}
  async function removeImage(image:ProductImage){if(!window.confirm("Bu görseli galeriden silmek istediğinize emin misiniz?"))return;const response=await fetch(`/api/product-images?id=${image.id}&productId=${id}`,{method:"DELETE"});setMessage(response.ok?"Görsel silindi.":"Görsel silinemedi.");if(response.ok)await load();}
  if(!product)return <main className="admin-shell"><a href="/admin">← Yönetim paneli</a><p>{message||"Ürün bulunamadı."}</p></main>;
  return <main className="admin-shell editor-shell"><header className="admin-header"><div><p>ÜRÜN DÜZENLEME</p><h1>{product.nameTr}</h1></div><div><a href={`/urun/${product.slug}`}>Ürünü gör ↗</a><a href="/admin">Panele dön ↗</a></div></header><section className="admin-card editor-card"><form onSubmit={save} className="admin-form"><label>Ürün adı<input name="nameTr" required defaultValue={product.nameTr}/></label><label>Ürün kodu / adresi<input name="slug" required defaultValue={product.slug}/></label><label className="wide">Kategori<select name="categoryId" defaultValue={product.categoryId??""}><option value="">Kategorisiz</option>{categories.map(c=><option key={c.id} value={c.id}>{c.parentId?"— ":""}{c.nameTr}</option>)}</select></label><label className="wide">Açıklama<textarea name="descriptionTr" rows={5} defaultValue={product.descriptionTr}/></label><label>Türkiye fiyatı<input name="priceTr" type="number" step="0.01" min="0" defaultValue={product.priceTr}/></label><label>Global fiyat (€)<input name="priceGlobal" type="number" step="0.01" min="0" defaultValue={product.priceGlobal}/></label><label>Stok<input name="stock" type="number" min="0" defaultValue={product.stock}/></label><label className="wide">Kapak görseli<input name="file" type="file" accept="image/*"/><small>veya mevcut bağlantı</small><input name="imageUrl" defaultValue={product.imageUrl}/></label><div className="checks wide"><label><input name="marketTr" type="checkbox" defaultChecked={product.marketTr}/> Türkiye</label><label><input name="marketGlobal" type="checkbox" defaultChecked={product.marketGlobal}/> Global</label><label><input name="active" type="checkbox" defaultChecked={product.active}/> Yayında</label></div><button disabled={busy}>{busy?"Kaydediliyor…":"Değişiklikleri kaydet"}</button></form>{message&&<p className="admin-message">{message}</p>}</section><section className="admin-card editor-card gallery-editor"><div className="list-title"><div><h2>Ürün galerisi</h2><p>Birden fazla görseli aynı anda seçebilir, kapak yapabilir veya silebilirsiniz.</p></div><span>{images.length} görsel</span></div><form onSubmit={uploadGallery} className="gallery-upload"><input name="galleryFiles" type="file" accept="image/*" multiple/><button disabled={busy}>{busy?"Yükleniyor…":"Seçilenleri yükle"}</button></form>{images.length===0?<p className="empty">Henüz galeri görseli eklenmedi.</p>:<div className="gallery-editor-grid">{images.map(image=><article key={image.id} className={product.imageUrl===image.imageUrl?"cover":""}><div><img src={image.imageUrl} alt={image.altText||product.nameTr}/>{product.imageUrl===image.imageUrl&&<span>KAPAK</span>}</div><button onClick={()=>makeCover(image)}>Kapak yap</button><button onClick={()=>removeImage(image)}>Sil</button></article>)}</div>}</section></main>;
}
