"use client";

import { useEffect, useState } from "react";
import "./politikalar.css";

type PolicySettings={shippingTr:string;freeShippingTr:string;shippingGlobal:string;freeShippingGlobal:string;shippingPolicyTr:string;returnsPolicyTr:string;shippingPolicyGlobal:string;returnsPolicyGlobal:string;privacyPolicy:string};
const defaults:PolicySettings={shippingTr:"99",freeShippingTr:"1500",shippingGlobal:"15",freeShippingGlobal:"150",shippingPolicyTr:"Sipariş talepleri onaylandıktan sonra hazırlanır. Teslimat süresi ürün ve teslimat adresine göre paylaşılır.",returnsPolicyTr:"İade veya değişim talebiniz için sipariş numaranızla bize ulaşın.",shippingPolicyGlobal:"Global order requests are reviewed before preparation. Delivery timing is confirmed according to destination.",returnsPolicyGlobal:"For a return or exchange request, contact us with your order number.",privacyPolicy:"Paylaştığınız bilgiler sipariş ve iletişim taleplerinizi işlemek amacıyla kaydedilir."};

export default function PoliciesPage(){const[market,setMarket]=useState<"TR"|"GLOBAL">("TR");const[settings,setSettings]=useState(defaults);useEffect(()=>{fetch("/api/settings").then(response=>response.json()).then(data=>data.settings&&setSettings(data.settings)).catch(()=>undefined);},[]);const isTr=market==="TR";return <main className="policies-page"><header className="policies-header"><a className="policies-brand" href="/">MYSA <span>OBJETS</span></a><nav><a href="/magaza">Mağaza</a><a href="/iletisim">Bize ulaşın</a></nav></header><section className="policies-hero"><p>BİLGİLENDİRME</p><h1>Teslimat, iade<br/><em>ve gizlilik.</em></h1><div className="policies-switch"><button className={isTr?"active":""} onClick={()=>setMarket("TR")}>Türkiye</button><button className={!isTr?"active":""} onClick={()=>setMarket("GLOBAL")}>Global</button></div></section><section className="policies-shell"><aside><span>Bu içerikler yönetim panelinden değiştirilebilir.</span><a href="/siparis-takip">Sipariş takibi →</a><a href="/iletisim">Destek talebi →</a></aside><div className="policies-content"><article><span>01</span><div><h2>{isTr?"Teslimat":"Shipping"}</h2><p>{isTr?settings.shippingPolicyTr:settings.shippingPolicyGlobal}</p><dl><div><dt>{isTr?"Standart kargo":"Standard shipping"}</dt><dd>{isTr?`${Number(settings.shippingTr).toLocaleString("tr-TR")} TL`:`€${Number(settings.shippingGlobal).toLocaleString("en-US")}`}</dd></div><div><dt>{isTr?"Ücretsiz kargo sınırı":"Free shipping threshold"}</dt><dd>{isTr?`${Number(settings.freeShippingTr).toLocaleString("tr-TR")} TL`:`€${Number(settings.freeShippingGlobal).toLocaleString("en-US")}`}</dd></div></dl></div></article><article><span>02</span><div><h2>{isTr?"İade ve değişim":"Returns & exchanges"}</h2><p>{isTr?settings.returnsPolicyTr:settings.returnsPolicyGlobal}</p><a href="/iletisim">{isTr?"Destek talebi oluştur":"Contact support"} →</a></div></article><article id="gizlilik"><span>03</span><div><h2>{isTr?"Gizlilik açıklaması":"Privacy notice"}</h2><p>{settings.privacyPolicy}</p><small>Bu sayfa genel operasyonel bilgilendirmedir. İşletme bilgileriniz ve satış modeliniz kesinleştiğinde nihai hukuki metinlerin ayrıca gözden geçirilmesi önerilir.</small></div></article></div></section></main>;}
