import {and,desc,eq,exists,gte,lte,notExists,sql} from "drizzle-orm";
import {getDb} from "../../../db";
import {inventoryMovements,products,productVariants} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTUser} from "../../chatgpt-auth";
import {containsLikelyCardNumber,readBoundedJson} from "../../public-form-security";
import {inventoryEligibleProduct} from "../../catalog-inventory";

const MAX_STOCK=1_000_000;

export async function GET(){
  if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401});
  const db=getDb();const[productRows,variantRows,movements]=await Promise.all([db.select().from(products).orderBy(desc(products.id)),db.select().from(productVariants),db.select().from(inventoryMovements).orderBy(desc(inventoryMovements.id)).limit(300)]);
  return Response.json({products:productRows,variants:variantRows,movements},{headers:{"Cache-Control":"no-store"}});
}

export async function PATCH(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});
  const parsed=await readBoundedJson(request,5_000);if(parsed.error)return parsed.error;const body=parsed.body!;const productId=Number(body.productId);const expectedUpdatedAt=String(body.expectedUpdatedAt??"");
  if(!Number.isInteger(productId)||productId<1)return Response.json({error:"Geçersiz ürün."},{status:400});
  if(!expectedUpdatedAt)return Response.json({error:"Tedarik profili ekranı güncel değil. Sayfayı yenileyip tekrar deneyin."},{status:409,headers:{"Cache-Control":"no-store"}});
  const sourcingType=String(body.sourcingType??"");if(!["factory","handmade"].includes(sourcingType))return Response.json({error:"Üretim türü fabrika veya el işçiliği olmalıdır."},{status:400});
  const unitCost=Number(body.unitCost);const leadTimeDays=Number(body.leadTimeDays);const reorderPoint=Number(body.reorderPoint);const supplierName=String(body.supplierName??"").trim();const supplierContact=String(body.supplierContact??"").trim();const supplierSku=String(body.supplierSku??"").trim();
  if(!Number.isFinite(unitCost)||unitCost<0||unitCost>1_000_000_000||!Number.isInteger(leadTimeDays)||leadTimeDays<0||leadTimeDays>365||!Number.isInteger(reorderPoint)||reorderPoint<0||reorderPoint>MAX_STOCK)return Response.json({error:"Maliyet, termin ve kritik stok değerlerini kontrol edin."},{status:400});if(supplierName.length>160||supplierContact.length>240||supplierSku.length>100)return Response.json({error:"Tedarik profili alanlarından biri izin verilen uzunluğu aşıyor."},{status:400});
  const db=getDb();const[before]=await db.select().from(products).where(eq(products.id,productId)).limit(1);if(!before)return Response.json({error:"Ürün bulunamadı."},{status:404});if(before.updatedAt!==expectedUpdatedAt)return Response.json({error:"Ürün veya stoğu bu sırada güncellendi. Sayfayı yenileyip tedarik profilini yeniden uygulayın."},{status:409,headers:{"Cache-Control":"no-store"}});const[product]=await db.update(products).set({sourcingType,supplierName,supplierContact,supplierSku,unitCost,leadTimeDays,reorderPoint,updatedAt:new Date().toISOString()}).where(and(eq(products.id,productId),inventoryEligibleProduct(),eq(products.updatedAt,expectedUpdatedAt))).returning();
  if(!product)return Response.json({error:"Ürün veya stoğu bu sırada güncellendi. Sayfayı yenileyip tedarik profilini yeniden uygulayın."},{status:409,headers:{"Cache-Control":"no-store"}});
  await recordAudit({user,action:"inventory.profile.update",entityType:"product",entityId:productId,summary:`${product.nameTr} tedarik bilgileri güncellendi.`,before:{sourcingType:before.sourcingType,supplierName:before.supplierName,unitCost:before.unitCost,leadTimeDays:before.leadTimeDays,reorderPoint:before.reorderPoint},after:{sourcingType,supplierName:product.supplierName,unitCost,leadTimeDays,reorderPoint}});
  return Response.json({product});
}

export async function POST(request:Request){
  const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401});
  const parsed=await readBoundedJson(request,5_000);if(parsed.error)return parsed.error;const body=parsed.body!;const productId=Number(body.productId);const rawVariantId=body.variantId===undefined||body.variantId===""?null:Number(body.variantId);const variantId=rawVariantId;const delta=Number(body.quantityDelta);const movementType=String(body.movementType??"");
  if(!Number.isInteger(productId)||productId<1||(variantId!==null&&(!Number.isInteger(variantId)||variantId<1))||!Number.isInteger(delta)||delta===0||Math.abs(delta)>100000||!["purchase","production","correction","damage","return"].includes(movementType))return Response.json({error:"Geçerli ürün, hareket türü ve sıfırdan farklı adet zorunludur."},{status:400});
  if(["purchase","production","return"].includes(movementType)&&delta<0)return Response.json({error:"Tedarik, üretim ve müşteri iadesi stok miktarını artırmalıdır."},{status:400});if(movementType==="damage"&&delta>0)return Response.json({error:"Hasar veya fire kaydı stok miktarını azaltmalıdır."},{status:400});
  const reason=String(body.reason??"").trim();const movementReference=String(body.reference??"").trim();if(reason.length<10||reason.length>500)return Response.json({error:"Stok hareketi için kısa bir açıklama zorunludur; 10–500 karakter kullanın."},{status:400});if(movementReference.length<3||movementReference.length>120)return Response.json({error:"Her manuel stok hareketi için 3–120 karakterlik benzersiz referans zorunludur."},{status:400});if(containsLikelyCardNumber(reason))return Response.json({error:"Stok açıklamasına kart numarası veya benzeri hassas ödeme verisi yazmayın."},{status:400});
  const db=getDb();const eligibleProduct=and(eq(products.id,productId),inventoryEligibleProduct());const[activeProduct]=await db.select({id:products.id}).from(products).where(eligibleProduct).limit(1);if(!activeProduct)return Response.json({error:"Ürün bulunamadı veya arşivde."},{status:404});const operationKey=`manual:${productId}:${variantId??0}:${movementType}:${movementReference.toLocaleLowerCase("tr-TR")}`;const movementLookup=db.select({id:inventoryMovements.id}).from(inventoryMovements).where(eq(inventoryMovements.operationKey,operationKey));const[duplicate]=await movementLookup.limit(1);if(duplicate)return Response.json({error:"Bu stok kalemi, hareket türü ve referans daha önce işlendi."},{status:409});const movementMissing=notExists(movementLookup);const productStillEligible=exists(db.select({id:products.id}).from(products).where(eligibleProduct));const now=new Date().toISOString();
  const stockUpdate=variantId?db.update(productVariants).set({stock:sql`${productVariants.stock} + ${delta}`,lastStockOperationKey:operationKey,updatedAt:now}).where(and(eq(productVariants.id,variantId),eq(productVariants.productId,productId),eq(productVariants.active,true),productStillEligible,delta<0?gte(productVariants.stock,-delta):lte(productVariants.stock,MAX_STOCK-delta),movementMissing)).returning({stock:productVariants.stock}):db.update(products).set({stock:sql`${products.stock} + ${delta}`,lastStockOperationKey:operationKey,updatedAt:now}).where(and(eligibleProduct,delta<0?gte(products.stock,-delta):lte(products.stock,MAX_STOCK-delta),movementMissing)).returning({stock:products.stock});
  const movementInsert=variantId?db.insert(inventoryMovements).select(db.select({operationKey:sql<string>`${operationKey}`,productId:sql<number>`${productId}`,variantId:sql<number>`${variantId}`,movementType:sql<string>`${movementType}`,quantityDelta:sql<number>`${delta}`,previousStock:sql<number>`${productVariants.stock}-${delta}`,nextStock:productVariants.stock,reason:sql<string>`${reason}`,reference:sql<string>`${movementReference}`,actorEmail:sql<string>`${user.email}`}).from(productVariants).where(and(eq(productVariants.id,variantId),eq(productVariants.productId,productId),eq(productVariants.active,true),productStillEligible,eq(productVariants.lastStockOperationKey,operationKey)))).onConflictDoNothing().returning():db.insert(inventoryMovements).select(db.select({operationKey:sql<string>`${operationKey}`,productId:sql<number>`${productId}`,variantId:sql<number|null>`NULL`,movementType:sql<string>`${movementType}`,quantityDelta:sql<number>`${delta}`,previousStock:sql<number>`${products.stock}-${delta}`,nextStock:products.stock,reason:sql<string>`${reason}`,reference:sql<string>`${movementReference}`,actorEmail:sql<string>`${user.email}`}).from(products).where(and(eligibleProduct,eq(products.lastStockOperationKey,operationKey)))).onConflictDoNothing().returning();
  const results=await db.batch([stockUpdate,movementInsert]);const stockResult=results[0][0];const movement=results[1][0];if(!stockResult||!movement){const[processed]=await db.select({id:inventoryMovements.id}).from(inventoryMovements).where(eq(inventoryMovements.operationKey,operationKey)).limit(1);return Response.json({error:processed?"Bu stok kalemi, hareket türü ve referans daha önce işlendi.":"Ürün bulunamadı, arşivde veya stok izin verilen sınırların dışına çıkamaz."},{status:409});}const nextStock=stockResult.stock;
  await recordAudit({user,action:"inventory.adjust",entityType:variantId?"variant":"product",entityId:variantId??productId,summary:`Stok ${delta>0?"artırıldı":"azaltıldı"}: ${delta>0?"+":""}${delta}.`,before:{stock:nextStock-delta},after:{stock:nextStock,movementType,reason}});
  return Response.json({movement,nextStock},{status:201});
}
