"use client";

import "./invoice-readiness.css";

type InvoiceOrder={orderNumber:string;status:string;paymentStatus:string;emailVerifiedAt:string|null;billingType:string;billingName:string;billingAddress:string;billingCity:string;billingPostalCode:string;billingCountry:string;billingTaxOffice:string;billingTaxNumber:string;pricingTaxStatus:string;sellerSnapshotJson:string;invoiceStatus:string;invoiceNumber:string;invoicedAt:string|null};
type Seller={legalStatus?:string;legalName?:string;legalAddress?:string;legalTaxOffice?:string;legalTaxNumber?:string};

export default function InvoiceReadiness({order}:{order:InvoiceOrder}){
  let seller:Seller={};try{seller=JSON.parse(order.sellerSnapshotJson||"{}")}catch{seller={}}
  const blockers=[...(!order.emailVerifiedAt?["Müşteri e-postası doğrulanmadı."]:[]),...(!order.billingName||!order.billingAddress||!order.billingCity||!order.billingCountry?["Fatura alıcı bilgileri eksik."]:[]),...(order.billingType==="corporate"&&(!order.billingTaxNumber||(!order.billingTaxOffice&&order.billingCountry==="Türkiye"))?["Kurumsal vergi bilgileri eksik."]:[]),...(order.pricingTaxStatus!=="tax_included"?["Sipariş anında fiyatların vergi durumu mali onay bekliyordu."]:[]),...(seller.legalStatus!=="complete"||!seller.legalName||!seller.legalAddress||!seller.legalTaxNumber?["Sipariş anındaki satıcı şirket bilgileri tamamlanmamıştı."]:[]),...(order.paymentStatus!=="paid"?["Ödeme kaydı tamamlanmadı."]:[]),...(order.status==="cancelled"?["Sipariş iptal edildi."]:[])];
  return <section className={`order-paper invoice-readiness ${blockers.length?"waiting":"ready"}`}><p className="invoice-kicker">FATURA KONTROLÜ</p><h2>{blockers.length?"Fatura taslağı bekliyor":"Fatura verileri hazır"}</h2><p>Bu ekran mali belge üretmez. Şirket ve e-fatura sağlayıcısı bağlandığında siparişin güvenli veri kaynağı olacaktır.</p><dl><div><dt>Alıcı</dt><dd>{order.billingName||"Eksik"}</dd></div><div><dt>Tür</dt><dd>{order.billingType==="corporate"?"Kurumsal":"Bireysel"}</dd></div><div><dt>Adres</dt><dd>{order.billingAddress?`${order.billingAddress}, ${order.billingPostalCode} ${order.billingCity}, ${order.billingCountry}`:"Eksik"}</dd></div>{order.billingType==="corporate"&&<><div><dt>Vergi dairesi</dt><dd>{order.billingTaxOffice||"—"}</dd></div><div><dt>Vergi no</dt><dd>{order.billingTaxNumber||"Eksik"}</dd></div></>}</dl>{blockers.length>0&&<ul>{blockers.map(item=><li key={item}>{item}</li>)}</ul>}{order.invoiceNumber&&<small>{order.invoiceNumber} · {order.invoicedAt?new Date(order.invoicedAt).toLocaleString("tr-TR"):order.invoiceStatus}</small>}</section>;
}
