"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import "./order-detail.css";
import "./order-totals.css";
import ShipmentManager from "./shipment-manager";

type Order = { id:number; orderNumber:string; market:string; status:string; customerName:string; email:string; phone:string; address:string; city:string; postalCode:string; country:string; note:string; subtotal:number; shippingAmount:number; total:number; paymentStatus:string; paymentProvider:string; paymentReference:string; shippingCarrier:string; trackingNumber:string; shippedAt:string|null; deliveryStatus:string; estimatedDeliveryAt:string|null; deliveredAt:string|null; internalNote:string; createdAt:string; updatedAt:string; reservationState:string; reservationExpiresAt:string|null; emailVerifiedAt:string|null; verificationExpiresAt:string|null };
type Line = { id:number; productName:string; variantLabel:string; quantity:number; unitPrice:number };
const labels:Record<string,string> = { new:"Yeni", confirmed:"Onaylandı", preparing:"Hazırlanıyor", shipped:"Kargoya verildi", completed:"Tamamlandı", cancelled:"İptal" };
const paymentLabels:Record<string,string>={pending:"Ödeme bekliyor",paid:"Ödendi",failed:"Başarısız",refunded:"İade edildi",not_required:"Ödeme gerekmiyor"};

export default function OrderDetail({ id }:{ id:number }) {
  const [order,setOrder] = useState<Order|null>(null);
  const [items,setItems] = useState<Line[]>([]);
  const [message,setMessage] = useState("Yükleniyor…");
  const load = useCallback(async () => { const response=await fetch(`/api/orders?id=${id}`); const data=await response.json(); if(response.ok){setOrder(data.order);setItems(data.items);setMessage("");}else setMessage(data.error??"Sipariş yüklenemedi."); },[id]);
  useEffect(()=>{void load();},[load]);
  async function updateStatus(status:string){const response=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const data=await response.json();setMessage(response.ok?"Sipariş durumu güncellendi.":data.error??"Durum güncellenemedi.");if(response.ok)await load();}
  async function saveOperations(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));if(values.estimatedDeliveryAt)values.estimatedDeliveryAt=new Date(String(values.estimatedDeliveryAt)).toISOString();const response=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...values})});const data=await response.json();setMessage(response.ok?"Ödeme ve kargo bilgileri kaydedildi.":data.error??"Operasyon bilgileri kaydedilemedi.");if(response.ok)await load();}
  if(!order)return <main className="order-state"><a href="/admin">← Yönetim paneli</a><p>{message}</p></main>;
  const money=(value:number)=>order.market==="TR"?`${value.toLocaleString("tr-TR")} TL`:`€${value.toLocaleString("en-US")}`;
  return <main className="order-detail-page">
    <header className="order-detail-header"><div><a href="/admin">← Yönetim paneli</a><p>SİPARİŞ DETAYI</p><h1>{order.orderNumber}</h1></div><div className="order-header-actions"><button onClick={()=>window.print()}>Yazdır</button><select value={order.status} onChange={event=>updateStatus(event.target.value)} aria-label="Sipariş durumu"><option value="new">Yeni</option><option value="confirmed">Onaylandı</option><option value="preparing">Hazırlanıyor</option><option value="shipped">Kargoya verildi</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal</option></select></div></header>
    {message&&<p className="order-message" role="status">{message}</p>}
    <section className="order-meta"><article><span>Durum</span><strong>{labels[order.status]??order.status}</strong></article><article><span>E-posta</span><strong>{order.emailVerifiedAt?`Doğrulandı · ${new Date(order.emailVerifiedAt).toLocaleString("tr-TR")}`:order.verificationExpiresAt?`Doğrulama bekliyor · ${new Date(order.verificationExpiresAt).toLocaleString("tr-TR")}`:"Doğrulanmadı"}</strong></article><article><span>Ödeme</span><strong>{paymentLabels[order.paymentStatus]??order.paymentStatus}</strong></article><article><span>Stok</span><strong>{order.reservationState==="active"?`Ayrıldı · ${order.reservationExpiresAt?new Date(order.reservationExpiresAt).toLocaleString("tr-TR"):"24 saat"}`:order.reservationState==="committed"?"Kesinleşti":order.reservationState==="expired"?"Süresi doldu":"Ayrılmadı"}</strong></article><article><span>Pazar</span><strong>{order.market}</strong></article><article><span>Toplam</span><strong>{money(order.total||order.subtotal)}</strong></article></section>
    <div className="order-detail-grid">
      <section className="order-paper"><div className="order-section-title"><h2>Ürünler</h2><span>{items.reduce((sum,item)=>sum+item.quantity,0)} adet</span></div>{items.map(item=><article className="order-line" key={item.id}><div><h3>{item.productName}</h3>{item.variantLabel&&<p>{item.variantLabel}</p>}<span>{item.quantity} × {money(item.unitPrice)}</span></div><strong>{money(item.unitPrice*item.quantity)}</strong></article>)}<div className="order-grand-total"><span>Ara toplam</span><strong>{money(order.subtotal)}</strong></div><div className="order-grand-total"><span>Teslimat</span><strong>{order.shippingAmount?money(order.shippingAmount):"Ücretsiz"}</strong></div><div className="order-grand-total order-final-total"><span>Genel toplam</span><strong>{money(order.total||order.subtotal)}</strong></div></section>
      <aside><section className="order-paper"><h2>Müşteri</h2><strong>{order.customerName}</strong><a href={`mailto:${order.email}`}>{order.email}</a><a href={`tel:${order.phone}`}>{order.phone}</a></section><section className="order-paper"><h2>Teslimat adresi</h2><address>{order.address}<br/>{order.postalCode&&<>{order.postalCode} </>}{order.city}<br/>{order.country}</address></section><section className="order-paper order-operations"><h2>Ödeme ve kargo</h2><form key={order.updatedAt} onSubmit={saveOperations}><label>Ödeme durumu<select name="paymentStatus" defaultValue={order.paymentStatus}><option value="pending">Ödeme bekliyor</option><option value="paid">Ödendi</option><option value="failed">Başarısız</option><option value="refunded">İade edildi</option><option value="not_required">Ödeme gerekmiyor</option></select></label><label>Ödeme sağlayıcısı<input name="paymentProvider" defaultValue={order.paymentProvider} placeholder="iyzico / PayTR"/></label><label>Ödeme referansı<input name="paymentReference" defaultValue={order.paymentReference} placeholder="İşlem numarası"/></label><label>Kargo firması<input name="shippingCarrier" defaultValue={order.shippingCarrier} placeholder="Yurtiçi Kargo"/></label><label>Takip numarası<input name="trackingNumber" defaultValue={order.trackingNumber} placeholder="Takip kodu"/></label><label>Tahmini teslim<input name="estimatedDeliveryAt" type="datetime-local" defaultValue={order.estimatedDeliveryAt?.slice(0,16)??""}/></label><label>İç operasyon notu<textarea name="internalNote" rows={4} defaultValue={order.internalNote} placeholder="Yalnızca yönetim panelinde görünür."/></label><button>Operasyon bilgilerini kaydet</button></form>{order.shippedAt&&<small>Kargoya verildi: {new Date(order.shippedAt).toLocaleString("tr-TR")}</small>}{order.deliveredAt&&<small>Teslim edildi: {new Date(order.deliveredAt).toLocaleString("tr-TR")}</small>}</section><ShipmentManager orderId={order.id} onChanged={load}/><section className="order-paper"><h2>Sipariş notu</h2><p>{order.note||"Müşteri not bırakmadı."}</p></section></aside>
    </div>
  </main>;
}
