"use client";

import {useCallback,useEffect,useState} from "react";
import "./packing-checklist.css";

type Checklist={productChecked:boolean;quantityChecked:boolean;qualityChecked:boolean;packageChecked:boolean;addressChecked:boolean;completedAt:string|null;actorEmail:string;updatedAt:string|null};
const steps=[{key:"productChecked",title:"Ürün ve varyant",copy:"Siparişteki ürün ve varyantlar fiziksel ürünlerle eşleşiyor."},{key:"quantityChecked",title:"Adet kontrolü",copy:"Her ürünün adedi sipariş kaydıyla aynı."},{key:"qualityChecked",title:"Kalite kontrolü",copy:"Kırık, leke, üretim kusuru ve görünür hasar yok."},{key:"packageChecked",title:"Güvenli paketleme",copy:"Koruyucu malzeme, kutu ve gerekli ekler tamam."},{key:"addressChecked",title:"Adres ve etiket",copy:"Alıcı, adres, telefon ve kargo etiketi son kez kontrol edildi."}] as const;

export default function PackingChecklist({orderId,status}:{orderId:number;status:string}){
  const[checklist,setChecklist]=useState<Checklist|null>(null);const[locked,setLocked]=useState(false);const[message,setMessage]=useState("Hazırlık listesi yükleniyor…");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/fulfillment-checklist?orderId=${orderId}`);const data=await response.json();if(response.ok){setChecklist(data.checklist);setLocked(data.locked);setMessage("")}else setMessage(data.error??"Hazırlık listesi alınamadı.")},[orderId]);useEffect(()=>{void load()},[load]);
  async function save(){if(!checklist)return;setBusy(true);const response=await fetch("/api/fulfillment-checklist",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId,...Object.fromEntries(steps.map(step=>[step.key,checklist[step.key]]))})});const data=await response.json();setMessage(response.ok?(data.complete?"Hazırlık tamamlandı; sipariş kargoya verilebilir.":"Hazırlık ilerlemesi kaydedildi."):data.error??"Hazırlık listesi kaydedilemedi.");if(response.ok)await load();setBusy(false);}
  const complete=checklist?steps.every(step=>checklist[step.key]):false;const editable=!locked&&["confirmed","preparing"].includes(status);
  return <section className={`order-paper packing-checklist ${complete?"complete":""}`}><div className="packing-head"><div><span>SİPARİŞ HAZIRLIĞI</span><h2>Paketleme kontrol listesi</h2></div><strong>{complete?"Kargoya hazır":"Kontrol gerekiyor"}</strong></div>{status==="new"&&<p className="packing-guidance">Kontrollere başlamadan önce müşteri doğrulamasını tamamlayıp siparişi onaylayın.</p>}{locked&&<p className="packing-guidance">Bu kayıt sipariş kargoya çıktığı, tamamlandığı veya iptal edildiği için kilitlendi.</p>}<div className="packing-steps">{checklist&&steps.map((step,index)=><label className={checklist[step.key]?"checked":""} key={step.key}><input type="checkbox" checked={checklist[step.key]} disabled={!editable||busy} onChange={event=>setChecklist({...checklist,[step.key]:event.target.checked})}/><i>{checklist[step.key]?"✓":index+1}</i><span><b>{step.title}</b><small>{step.copy}</small></span></label>)}</div>{message&&<p className="packing-message" role="status">{message}</p>}<div className="packing-footer"><small>{checklist?.completedAt?`Tamamlandı · ${new Date(checklist.completedAt).toLocaleString("tr-TR")}`:checklist?.updatedAt?`Son kayıt · ${new Date(checklist.updatedAt).toLocaleString("tr-TR")}`:"Henüz kayıt yok"}</small><button onClick={save} disabled={!editable||busy||!checklist}>{busy?"Kaydediliyor…":"Kontrolleri kaydet"}</button></div></section>;
}
