"use client";

import {useEffect,useMemo,useState} from "react";
import "./cart-notice.css";
import "./gallery.css";

type Product={id:number;slug:string;nameTr:string;nameEn:string;descriptionTr:string;descriptionEn:string;imageUrl:string;priceTr:number;priceGlobal:number;stock:number;marketTr:boolean;marketGlobal:boolean;active:boolean};
type Variant={id:number;productId:number;optionName:string;optionValue:string;optionNameEn:string;optionValueEn:string;sku:string;stock:number;priceAdjustment:number};
type ProductImage={id:number;productId:number;imageUrl:string;altText:string;sortOrder:number};

export default function ProductDetail({slug}:{slug:string}){
  const[product,setProduct]=useState<Product|null>(null);const[variants,setVariants]=useState<Variant[]>([]);const[gallery,setGallery]=useState<ProductImage[]>([]);const[activeImage,setActiveImage]=useState("");const[selected,setSelected]=useState<number|null>(null);const[market,setMarket]=useState<"TR"|"GLOBAL">("TR");const[status,setStatus]=useState("Yükleniyor…");
  useEffect(()=>{Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/variants").then(r=>r.json())]).then(async([p,v])=>{const found=(p.products??[]).find((item:Product)=>item.slug===decodeURIComponent(slug)&&item.active);setProduct(found??null);if(found){const own=(v.variants??[]).filter((item:Variant)=>item.productId===found.id);setVariants(own);setSelected(own[0]?.id??null);const data=await fetch(`/api/product-images?productId=${found.id}`).then(r=>r.json());setGallery(data.images??[]);setActiveImage(found.imageUrl||(data.images??[])[0]?.imageUrl||"");setStatus("");}else setStatus("Ürün bulunamadı.");}).catch(()=>setStatus("Ürün yüklenemedi."));},[slug]);
  const choice=useMemo(()=>variants.find(v=>v.id===selected),[variants,selected]);
  const displayImages=useMemo(()=>{if(!product)return[];const primary=product.imageUrl?[{id:0,productId:product.id,imageUrl:product.imageUrl,altText:product.nameTr,sortOrder:-1}]:[];return[...primary,...gallery.filter(image=>image.imageUrl!==product.imageUrl)];},[product,gallery]);
  async function addToCart(){if(!product)return;const response=await fetch("/api/cart",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:product.id,variantId:choice?.id??null,quantity:1,market})});setStatus(response.ok?(market==="TR"?"Ürün çantanıza eklendi.":"Product added to your bag."):(market==="TR"?"Ürün eklenemedi.":"Product could not be added."));}
  if(!product)return <main className="detail-state"><a href="/magaza">← Mağazaya dön</a><p>{status}</p></main>;
  const base=market==="TR"?product.priceTr:product.priceGlobal;const total=base+(choice?.priceAdjustment??0);const currency=market==="TR"?"TL":"€";const fallback="https://images.unsplash.com/photo-1616627547584-bf28cee262db?auto=format&fit=crop&w=1200&q=88";const displayName=market==="GLOBAL"?(product.nameEn||product.nameTr):product.nameTr;const displayDescription=market==="GLOBAL"?(product.descriptionEn||product.descriptionTr):product.descriptionTr;const optionName=(variant:Variant)=>market==="GLOBAL"?(variant.optionNameEn||variant.optionName):variant.optionName;const optionValue=(variant:Variant)=>market==="GLOBAL"?(variant.optionValueEn||variant.optionValue):variant.optionValue;
  return <main className="detail-page">
    <header className="detail-header"><a className="detail-brand" href="/">MYSA <span>OBJETS</span></a><div><a href="/magaza">{market==="TR"?"Mağazaya dön":"Back to shop"} ↗</a><a href="/sepet">{market==="TR"?"Çanta":"Bag"} ↗</a></div></header>
    <section className="detail-grid">
      <div className="detail-image detail-gallery"><div className="detail-gallery-main"><img src={activeImage||fallback} alt={displayName}/><span>{displayImages.length>1?`${displayImages.findIndex(image=>image.imageUrl===(activeImage||product.imageUrl))+1} / ${displayImages.length}`:""}</span></div>{displayImages.length>1&&<div className="detail-thumbs">{displayImages.map(image=><button key={image.id} className={activeImage===image.imageUrl?"active":""} onClick={()=>setActiveImage(image.imageUrl)} aria-label={`${displayName} image`}><img src={image.imageUrl} alt={image.altText||displayName}/></button>)}</div>}</div>
      <div className="detail-copy"><p className="detail-eyebrow">{market==="TR"?"SEÇKİLİ ÜRÜN":"CURATED PRODUCT"}</p><h1>{displayName}</h1><p className="detail-description">{displayDescription||(market==="TR"?"Bu ürün için ayrıntılı açıklama yakında eklenecek.":"Detailed product information will be added soon.")}</p><div className="detail-market"><button className={market==="TR"?"active":""} disabled={!product.marketTr} onClick={()=>setMarket("TR")}>Türkiye</button><button className={market==="GLOBAL"?"active":""} disabled={!product.marketGlobal} onClick={()=>setMarket("GLOBAL")}>Global</button></div>{variants.length>0&&<div className="detail-options"><label>{optionName(variants[0])}</label><div>{variants.map(variant=><button key={variant.id} className={selected===variant.id?"active":""} disabled={variant.stock<1} onClick={()=>setSelected(variant.id)}>{optionValue(variant)}</button>)}</div></div>}<div className="detail-price"><strong>{market==="TR"?`${total.toLocaleString("tr-TR")} ${currency}`:`${currency}${total}`}</strong><span>{choice?`${choice.stock} ${market==="TR"?"adet mevcut":"in stock"}`:product.stock>0?`${product.stock} ${market==="TR"?"adet mevcut":"in stock"}`:market==="TR"?"Tükendi":"Sold out"}</span></div><button className="detail-cart" onClick={addToCart} disabled={(choice?.stock??product.stock)<1}>{market==="TR"?"Çantaya ekle":"Add to bag"}</button>{status&&<p className="detail-notice">{status} {(status.includes("eklendi")||status.includes("added"))&&<a href="/sepet">{market==="TR"?"Çantayı görüntüle":"View bag"} →</a>}</p>}<div className="detail-services"><span>{market==="TR"?"Güvenli ödeme":"Secure payment"}</span><span>{market==="TR"?"Özenli paketleme":"Careful packaging"}</span><span>{market==="TR"?"Kolay iade":"Easy returns"}</span></div></div>
    </section>
  </main>;
}
