import {desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {newsletterOutbox,newsletterSubscribers} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTOwner} from "../../chatgpt-auth";
import {enforceRateLimit} from "../../rate-limit";
import {createVerificationToken,hashVerificationToken} from "../../order-verification";
import {isValidEmail,normalizeEmail,readBoundedJson} from "../../public-form-security";
import {createNewsletterVerification,unsubscribeNewsletterSubscriber} from "../../newsletter-subscription";

export const dynamic="force-dynamic";const noStore={"Cache-Control":"no-store"};

export async function GET(){if(!(await getChatGPTOwner()))return Response.json({error:"Bülten kayıtları yalnızca mağaza sahibine açıktır."},{status:403,headers:noStore});const db=getDb();const[subscribers,outbox]=await Promise.all([db.select({id:newsletterSubscribers.id,email:newsletterSubscribers.email,market:newsletterSubscribers.market,status:newsletterSubscribers.status,consentAt:newsletterSubscribers.consentAt,verificationExpiresAt:newsletterSubscribers.verificationExpiresAt,verifiedAt:newsletterSubscribers.verifiedAt,unsubscribedAt:newsletterSubscribers.unsubscribedAt,updatedAt:newsletterSubscribers.updatedAt}).from(newsletterSubscribers).orderBy(desc(newsletterSubscribers.id)),db.select({id:newsletterOutbox.id,subscriberId:newsletterOutbox.subscriberId,eventType:newsletterOutbox.eventType,recipient:newsletterOutbox.recipient,subject:newsletterOutbox.subject,status:newsletterOutbox.status,attempts:newsletterOutbox.attempts,lastError:newsletterOutbox.lastError,sentAt:newsletterOutbox.sentAt,createdAt:newsletterOutbox.createdAt,updatedAt:newsletterOutbox.updatedAt}).from(newsletterOutbox).orderBy(desc(newsletterOutbox.id)).limit(500)]);return Response.json({subscribers,outbox},{headers:noStore});}

export async function POST(request:Request){const parsed=await readBoundedJson(request);if(parsed.error)return parsed.error;const body=parsed.body!;if(String(body.company??"").trim())return Response.json({ok:true},{status:201,headers:noStore});const email=normalizeEmail(body.email);const market=body.market==="GLOBAL"?"GLOBAL":"TR";if(!isValidEmail(email)||body.consent!==true)return Response.json({error:"Geçerli e-posta adresi ve bülten onayı zorunludur."},{status:400,headers:noStore});const limited=await enforceRateLimit(request,{scope:"newsletter",identifier:email,limit:5,windowMinutes:60});if(limited)return limited;const db=getDb();const[existing]=await db.select().from(newsletterSubscribers).where(eq(newsletterSubscribers.email,email)).limit(1);if(existing?.status==="active")return Response.json({ok:true,alreadyActive:true},{status:200,headers:noStore});if(existing?.status==="pending_verification"&&Date.now()-new Date(existing.updatedAt).getTime()<10*60_000)return Response.json({ok:true,pendingVerification:true,cooldown:true},{status:202,headers:noStore});const verificationToken=createVerificationToken();const unsubscribeToken=createVerificationToken();const verificationTokenHash=await hashVerificationToken(verificationToken);const unsubscribeTokenHash=await hashVerificationToken(unsubscribeToken);const now=new Date().toISOString();const verificationExpiresAt=new Date(Date.now()+48*60*60*1000).toISOString();const verifyUrl=`https://mysa-objets-store.robologai.chatgpt.site/bulten-dogrula?token=${verificationToken}`;const unsubscribeUrl=`https://mysa-objets-store.robologai.chatgpt.site/bulten-tercihi?token=${unsubscribeToken}`;const result=await createNewsletterVerification(db,{email,market,verificationTokenHash,unsubscribeTokenHash,verificationExpiresAt,subject:market==="GLOBAL"?"Confirm your MYSA OBJETS subscription":"MYSA OBJETS bülten kaydınızı doğrulayın",body:market==="GLOBAL"?`Confirm your subscription within 48 hours: ${verifyUrl}\n\nUnsubscribe: ${unsubscribeUrl}`:`Bülten kaydınızı 48 saat içinde doğrulayın: ${verifyUrl}\n\nAbonelikten çık: ${unsubscribeUrl}`,now});if(result==="active")return Response.json({ok:true,alreadyActive:true},{status:200,headers:noStore});if(result!=="queued")return Response.json({error:"Bülten doğrulama isteği bu sırada değişti. Lütfen tekrar deneyin."},{status:409,headers:noStore});return Response.json({ok:true,pendingVerification:true},{status:201,headers:noStore});}

export async function PATCH(request:Request){const user=await getChatGPTOwner();if(!user)return Response.json({error:"Bülten kayıtlarını yalnızca mağaza sahibi yönetebilir."},{status:403,headers:noStore});const parsed=await readBoundedJson(request,2_000);if(parsed.error)return parsed.error;const id=Number(parsed.body?.id);if(!Number.isInteger(id)||id<1||parsed.body?.status!=="unsubscribed")return Response.json({error:"Abonelik yalnızca doğrulama bağlantısıyla aktifleştirilebilir."},{status:400,headers:noStore});const db=getDb();const[before]=await db.select().from(newsletterSubscribers).where(eq(newsletterSubscribers.id,id)).limit(1);if(!before)return Response.json({error:"Abone bulunamadı"},{status:404,headers:noStore});const now=new Date().toISOString();const subscriber=await unsubscribeNewsletterSubscriber(db,{id,expectedUpdatedAt:before.updatedAt,now});if(!subscriber)return Response.json({error:"Abonelik bu sırada başka bir işlem tarafından güncellendi. Güncel listeyi açıp tekrar deneyin."},{status:409,headers:noStore});await recordAudit({user,action:"newsletter.unsubscribe",entityType:"newsletter_subscriber",entityId:id,summary:`${before.email} bülten aboneliği yönetim tarafından durduruldu.`,before:{status:before.status},after:{status:"unsubscribed"}});return Response.json({subscriber},{headers:noStore});}
