import {and,desc,eq} from "drizzle-orm";
import {getDb} from "../../../db";
import {newsletterOutbox,newsletterSubscribers} from "../../../db/schema";
import {recordAudit} from "../../audit-log";
import {getChatGPTUser} from "../../chatgpt-auth";
import {enforceRateLimit} from "../../rate-limit";
import {createVerificationToken,hashVerificationToken} from "../../order-verification";
import {isValidEmail,normalizeEmail,readBoundedJson} from "../../public-form-security";

export const dynamic="force-dynamic";const noStore={"Cache-Control":"no-store"};

export async function GET(){if(!(await getChatGPTUser()))return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const db=getDb();const[subscribers,outbox]=await Promise.all([db.select().from(newsletterSubscribers).orderBy(desc(newsletterSubscribers.id)),db.select().from(newsletterOutbox).orderBy(desc(newsletterOutbox.id)).limit(500)]);return Response.json({subscribers,outbox},{headers:noStore});}

export async function POST(request:Request){const parsed=await readBoundedJson(request);if(parsed.error)return parsed.error;const body=parsed.body!;if(String(body.company??"").trim())return Response.json({ok:true},{status:201,headers:noStore});const email=normalizeEmail(body.email);const market=body.market==="GLOBAL"?"GLOBAL":"TR";if(!isValidEmail(email)||body.consent!==true)return Response.json({error:"Geçerli e-posta adresi ve bülten onayı zorunludur."},{status:400,headers:noStore});const limited=await enforceRateLimit(request,{scope:"newsletter",identifier:email,limit:5,windowMinutes:60});if(limited)return limited;const db=getDb();const[existing]=await db.select().from(newsletterSubscribers).where(eq(newsletterSubscribers.email,email)).limit(1);if(existing?.status==="active")return Response.json({ok:true,alreadyActive:true},{status:200,headers:noStore});if(existing?.status==="pending_verification"&&Date.now()-new Date(existing.updatedAt).getTime()<10*60_000)return Response.json({ok:true,pendingVerification:true,cooldown:true},{status:202,headers:noStore});const verificationToken=createVerificationToken();const unsubscribeToken=createVerificationToken();const verificationTokenHash=await hashVerificationToken(verificationToken);const unsubscribeTokenHash=await hashVerificationToken(unsubscribeToken);const now=new Date().toISOString();const verificationExpiresAt=new Date(Date.now()+48*60*60*1000).toISOString();const[subscriber]=await db.insert(newsletterSubscribers).values({email,market,status:"pending_verification",consentAt:now,verificationTokenHash,verificationExpiresAt,unsubscribeTokenHash,unsubscribedAt:null,updatedAt:now}).onConflictDoUpdate({target:newsletterSubscribers.email,set:{market,status:"pending_verification",consentAt:now,verificationTokenHash,verificationExpiresAt,unsubscribeTokenHash,unsubscribedAt:null,updatedAt:now}}).returning();await db.update(newsletterOutbox).set({status:"cancelled",updatedAt:now}).where(and(eq(newsletterOutbox.subscriberId,subscriber.id),eq(newsletterOutbox.status,"draft")));const verifyUrl=`https://mysa-objets-store.robologai.chatgpt.site/bulten-dogrula?token=${verificationToken}`;const unsubscribeUrl=`https://mysa-objets-store.robologai.chatgpt.site/bulten-tercihi?token=${unsubscribeToken}`;await db.insert(newsletterOutbox).values({subscriberId:subscriber.id,eventKey:`newsletter:${subscriber.id}:verify:${verificationTokenHash.slice(0,16)}`,eventType:"verification",recipient:email,subject:market==="GLOBAL"?"Confirm your MYSA OBJETS subscription":"MYSA OBJETS bülten kaydınızı doğrulayın",body:market==="GLOBAL"?`Confirm your subscription within 48 hours: ${verifyUrl}\n\nUnsubscribe: ${unsubscribeUrl}`:`Bülten kaydınızı 48 saat içinde doğrulayın: ${verifyUrl}\n\nAbonelikten çık: ${unsubscribeUrl}`,status:"draft"});return Response.json({ok:true,pendingVerification:true},{status:201,headers:noStore});}

export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:"Yetkisiz erişim"},{status:401,headers:noStore});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const id=Number(body?.id);if(!id||body?.status!=="unsubscribed")return Response.json({error:"Abonelik yalnızca doğrulama bağlantısıyla aktifleştirilebilir."},{status:400,headers:noStore});const db=getDb();const[before]=await db.select().from(newsletterSubscribers).where(eq(newsletterSubscribers.id,id)).limit(1);if(!before)return Response.json({error:"Abone bulunamadı"},{status:404,headers:noStore});const now=new Date().toISOString();const[subscriber]=await db.update(newsletterSubscribers).set({status:"unsubscribed",unsubscribedAt:now,verificationTokenHash:"",verificationExpiresAt:null,unsubscribeTokenHash:"",updatedAt:now}).where(eq(newsletterSubscribers.id,id)).returning();await recordAudit({user,action:"newsletter.unsubscribe",entityType:"newsletter_subscriber",entityId:id,summary:`${before.email} bülten aboneliği yönetim tarafından durduruldu.`,before:{status:before.status},after:{status:"unsubscribed"}});return Response.json({subscriber},{headers:noStore});}
