"use client";

import {useEffect,useState} from "react";

type Channel={provider:string;mode:"sandbox"|"live"|"unconfigured";credentialsConfigured:boolean;adapterConnected:boolean;keys:Record<string,boolean>;blockers:string[]};
type Status={payment:Channel;email:Channel;paymentWebhook:{retainedRecent:number;awaitingAdapter:number;lastReceivedAt:string|null}};
const keyLabels:Record<string,string>={PAYMENT_PROVIDER:"Sağlayıcı adı",PAYMENT_MODE:"Test / canlı modu",PAYMENT_SECRET_KEY:"Gizli API anahtarı",PAYMENT_WEBHOOK_SECRET:"Webhook imza anahtarı",EMAIL_PROVIDER:"Sağlayıcı adı",EMAIL_MODE:"Test / canlı modu",EMAIL_API_KEY:"Gizli API anahtarı",EMAIL_FROM:"Doğrulanmış gönderici"};

function ChannelCard({title,description,channel}:{title:string;description:string;channel:Channel}){
  return <article className="admin-card integration-card"><header><div><p className="section-kicker">{channel.mode==="live"?"CANLI":channel.mode==="sandbox"?"TEST ORTAMI":"YAPILANDIRILMADI"}</p><h2>{title}</h2></div><span className={channel.adapterConnected?"connected":"waiting"}>{channel.adapterConnected?"Bağlı":"Kapalı"}</span></header><p>{description}</p><dl><div><dt>Sağlayıcı</dt><dd>{channel.provider||"Henüz seçilmedi"}</dd></div><div><dt>Ortam</dt><dd>{channel.mode==="live"?"Canlı":channel.mode==="sandbox"?"Sandbox / test":"Belirlenmedi"}</dd></div><div><dt>Kimlik bilgileri</dt><dd>{channel.credentialsConfigured?"Eksiksiz":"Eksik"}</dd></div><div><dt>Adaptör</dt><dd>{channel.adapterConnected?"Etkin":"Sağlayıcı seçimini bekliyor"}</dd></div></dl><div className="integration-keys">{Object.entries(channel.keys).map(([key,ready])=><span className={ready?"ready":"missing"} key={key}><i>{ready?"✓":"!"}</i>{keyLabels[key]??key}</span>)}</div><ul>{channel.blockers.map(blocker=><li key={blocker}>{blocker}</li>)}</ul></article>;
}

export default function IntegrationCenter(){
  const[data,setData]=useState<Status|null>(null);const[message,setMessage]=useState("Yükleniyor…");
  useEffect(()=>{fetch("/api/integrations/status").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setData({...result.integrations,paymentWebhook:result.paymentWebhook});setMessage("");}).catch(error=>setMessage(error instanceof Error?error.message:"Entegrasyon durumu yüklenemedi."));},[]);
  return <main className="admin-shell integrations-shell"><header className="admin-header"><div><p>SAĞLAYICI ALTYAPISI</p><h1>Ödeme ve e-posta entegrasyonları</h1></div><div><a href="/admin">Panele dön ↗</a><a href="/admin/yayina-hazirlik">Yayına hazırlık ↗</a></div></header><section className="integration-intro"><div><b>Gizli anahtarlar yönetim ekranında gösterilmez.</b><p>Şirket ve sağlayıcı sözleşmeleri tamamlandıktan sonra değerler güvenli çalışma ortamına eklenir. Test modu doğrulanmadan canlı moda geçilmez.</p></div><span>Şu anda gerçek ödeme ve otomatik e-posta gönderimi kapalıdır.</span></section>{!data?<section className="admin-card">{message}</section>:<><section className="integration-grid"><ChannelCard title="Ödeme sağlayıcısı" description="Ödeme başlatma, sonuç doğrulama ve imzalı webhook akışı için hazırlanmıştır." channel={data.payment}/><ChannelCard title="E-posta sağlayıcısı" description="Sipariş bildirim taslaklarının doğrulanmış gönderici üzerinden iletilmesi için hazırlanmıştır." channel={data.email}/></section><section className="admin-card integration-sequence"><p className="section-kicker">GÜVENLİ BAĞLANTI SIRASI</p><h2>Sağlayıcı seçildikten sonra</h2><ol><li><b>Sandbox hesabını açın</b><span>Sağlayıcı adı ve yalnızca test anahtarları eklenir.</span></li><li><b>Webhook imzasını doğrulayın</b><span>İmzasız, eski zaman damgalı veya değiştirilmiş olaylar reddedilir.</span></li><li><b>Test siparişini tamamlayın</b><span>Başarılı, başarısız ve yinelenen ödeme olayları ayrı ayrı sınanır.</span></li><li><b>Canlı anahtarları ayrı girin</b><span>Test anahtarlarının üzerine yazılmaz; ortam modu ayrıca “live” yapılır.</span></li><li><b>Kontrollü açılış yapın</b><span>İlk gerçek işlem yönetim paneli ve sağlayıcı panelinden birlikte doğrulanır.</span></li></ol></section><section className="admin-card webhook-note"><b>Webhook güvenlik durumu</b><p>Ödeme webhook adresi hazırdır ancak yapılandırma tamamlanmadan <code>503</code> döner. Geçerli HMAC-SHA256 imzası, olay kimliği ve beş dakikadan yeni zaman damgası olmadan olay kabul edilmez. Ham ödeme içeriği saklanmaz; son 100 güvenli alındı kaydından {data.paymentWebhook.retainedRecent} tanesi görülüyor, {data.paymentWebhook.awaitingAdapter} tanesi sağlayıcı adaptörünü bekliyor.{data.paymentWebhook.lastReceivedAt?` Son alım: ${new Date(data.paymentWebhook.lastReceivedAt).toLocaleString("tr-TR")}.`:""} Adaptör etkinleşmeden doğrulanmış olaylar dahi sipariş veya ödeme durumunu değiştiremez.</p></section></>}</main>;
}
